// Generate/prune the personal autocomplete wrapper skills for strapped chains:
// one thin skill per resolvable chain at ~/.claude/skills/strapped-run-<chain>/
// SKILL.md whose body only delegates to /strapped:run <chain>. Best-effort
// sugar — /strapped:run stays the canonical entry.
//
// Usage (one JSON object on stdout; misuse = one-line stderr + exit 1):
//   sync-chain-skills.mjs [--home <dir>] [--dry-run]   → { written, unchanged, pruned }
//
// Contract (conventions.md "Wrapper skill sync"):
// - every generated wrapper carries `generated_by: strapped` frontmatter;
//   files WITHOUT that marker are NEVER overwritten or deleted.
// - `chain_source: builtin | anchor` records where the chain resolved from.
// - idempotent: a byte-identical wrapper is a no-op (reported `unchanged`).
// - global prune rule: chain resolution is global (built-ins + anchor,
//   cwd-independent), so a marked wrapper whose chain no longer resolves is
//   pruned; unmarked directories are untouched.
// - --dry-run prints the planned writes/prunes and mutates nothing.
//
// Zero dependencies. Chain resolution is delegated to resolve-chain.mjs
// (--list) so there is exactly one resolver — resolved as a sibling of the
// DEPLOYED artifact via import.meta.url, spawned under process.execPath
// (node, in the deployed artifact).

import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { getProp } from '../lib/anchor.ts'
import { die as cliDie, out } from '../lib/cli.ts'

const RESOLVE_CHAIN_SCRIPT = fileURLToPath(new URL('./resolve-chain.mjs', import.meta.url))
const WRAPPER_PREFIX = 'strapped-run-'
const MARKER_LINE = /^generated_by: strapped$/m

// Deployed artifact keeps the historical name in every message. The explicit
// `never`-returning annotation on the const is what lets tsc treat die() calls
// as control-flow endpoints (an arrow-only annotation is not enough).
const die: (msg: string) => never = msg => cliDie('sync-chain-skills.mjs', msg)

const warn = (msg: string): void => {
  process.stderr.write(`sync-chain-skills.mjs: ${msg}\n`)
}

// --- args --------------------------------------------------------------------

const args = process.argv.slice(2)
let home: string | null = null
let dryRun = false
for (let i = 0; i < args.length; i++) {
  if (args[i] === '--home') {
    const value = args[i + 1]
    if (!value) die('--home requires a value')
    home = value
    i++
  } else if (args[i] === '--dry-run') {
    dryRun = true
  } else {
    die('usage: sync-chain-skills.mjs [--home <dir>] [--dry-run]')
  }
}
const resolvedHome = home || process.env.HOME || homedir()

// --- resolve chains (the one resolver: resolve-chain.mjs --list) --------------

interface Chain {
  name: string
  stages: string[]
  source: string
}

function isChain(value: unknown): value is Chain {
  return (
    typeof getProp(value, 'name') === 'string' &&
    Array.isArray(getProp(value, 'stages')) &&
    typeof getProp(value, 'source') === 'string'
  )
}

const res = spawnSync(process.execPath, [RESOLVE_CHAIN_SCRIPT, '--list'], {
  encoding: 'utf8',
  env: { ...process.env, HOME: resolvedHome },
})
if (res.status !== 0) {
  process.stderr.write(res.stderr || 'sync-chain-skills.mjs: chain resolution failed\n')
  process.exit(1)
}
const parsed: unknown = JSON.parse(res.stdout)
const chainList = getProp(parsed, 'chains')
if (!Array.isArray(chainList)) die('unexpected resolve-chain.mjs --list output: no chains array')
const chains: Chain[] = []
for (const raw of chainList) {
  if (!isChain(raw)) die(`unexpected resolve-chain.mjs --list output: malformed chain entry ${JSON.stringify(raw)}`)
  chains.push(raw)
}

// --- write/refresh wrappers ----------------------------------------------------

const skillsDir = join(resolvedHome, '.claude', 'skills')

function wrapperContent(chain: Chain): string {
  return `---
name: ${WRAPPER_PREFIX}${chain.name}
description: Run the strapped '${chain.name}' chain (${chain.stages.join(', ')}) to completion — generated by strapped, do not edit
generated_by: strapped
chain_source: ${chain.source}
---

Invoke the Skill (slash command) \`/strapped:run ${chain.name} $ARGUMENTS\` — this wrapper only delegates to the canonical \`/strapped:run\` entry point.
`
}

const written: string[] = []
const unchanged: string[] = []
const pruned: string[] = []

for (const chain of chains) {
  const dir = join(skillsDir, `${WRAPPER_PREFIX}${chain.name}`)
  const file = join(dir, 'SKILL.md')
  const content = wrapperContent(chain)
  if (existsSync(file)) {
    const current = readFileSync(file, 'utf8')
    if (current === content) {
      unchanged.push(chain.name)
      continue
    }
    if (!MARKER_LINE.test(current)) {
      warn(`skipping ${file}: exists without the "generated_by: strapped" marker — not ours, never touched`)
      continue
    }
  }
  written.push(chain.name)
  if (!dryRun) {
    mkdirSync(dir, { recursive: true })
    writeFileSync(file, content)
  }
}

// --- prune stale marked wrappers ------------------------------------------------

const liveDirs = new Set(chains.map(c => `${WRAPPER_PREFIX}${c.name}`))
if (existsSync(skillsDir)) {
  for (const entry of readdirSync(skillsDir)) {
    if (!entry.startsWith(WRAPPER_PREFIX) || liveDirs.has(entry)) continue
    const dir = join(skillsDir, entry)
    if (!statSync(dir).isDirectory()) continue
    const file = join(dir, 'SKILL.md')
    // No SKILL.md, or one without the marker → not ours, never touched.
    if (!existsSync(file) || !MARKER_LINE.test(readFileSync(file, 'utf8'))) continue
    pruned.push(entry.slice(WRAPPER_PREFIX.length))
    if (!dryRun) rmSync(dir, { recursive: true })
  }
}

pruned.sort()
out({ written, unchanged, pruned })
