#!/usr/bin/env node
// GENERATED by tools/build.ts from src/scripts/resolve-chain.ts — do not edit; rebuild: bun run build
// src/lib/anchor.ts
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { isAbsolute, join } from "node:path";
function anchorPath() {
  const home = process.env.HOME || homedir();
  return join(home, ".claude", "strapped.json");
}
function readAnchor() {
  const path = anchorPath();
  if (!existsSync(path))
    return;
  return JSON.parse(readFileSync(path, "utf8"));
}
function getProp(value, key) {
  if (typeof value === "object" && value !== null && key in value) {
    return value[key];
  }
  return;
}

// src/lib/cli.ts
function die(prefix, msg) {
  process.stderr.write(`${prefix}: ${msg}
`);
  process.exit(1);
}
function out(obj) {
  process.stdout.write(JSON.stringify(obj) + `
`);
}

// src/scripts/resolve-chain.ts
var die2 = (msg) => die("resolve-chain.mjs", msg);
var VALID_STAGES = ["plan", "implement", "pr"];
var EXCLUDED_STAGES = new Set(["feedback", "learn", "status"]);
var NAME_SHAPE = /^[A-Za-z][A-Za-z0-9_-]*$/;
var BUILTINS = {
  auto: ["plan", "implement", "pr"],
  ship: ["implement", "pr"]
};
function validateChain({ name, stages, source }) {
  if (!NAME_SHAPE.test(name)) {
    die2(`chain "${name}" (${source}): invalid name — chain names must match ${NAME_SHAPE} (they become skill directory names)`);
  }
  if (!Array.isArray(stages)) {
    die2(`chain "${name}" (${source}): stages must be an array of stage names — valid stages: ${VALID_STAGES.join(", ")}`);
  }
  const list = stages;
  if (list.length === 0) {
    die2(`chain "${name}" (${source}): empty — a chain must list at least one of: ${VALID_STAGES.join(", ")}`);
  }
  const seen = new Set;
  const validated = [];
  let prev = -1;
  for (const raw of list) {
    if (typeof raw !== "string" || !VALID_STAGES.includes(raw)) {
      const why = typeof raw === "string" && EXCLUDED_STAGES.has(raw) ? " (interactive by design — excluded from chains)" : "";
      die2(`chain "${name}" (${source}): unknown stage "${String(raw)}"${why} — valid stages: ${VALID_STAGES.join(", ")}`);
    }
    const stage = raw;
    const idx = VALID_STAGES.indexOf(stage);
    if (seen.has(stage)) {
      die2(`chain "${name}" (${source}): duplicate stage "${stage}" — each stage may appear at most once`);
    }
    if (idx < prev) {
      die2(`chain "${name}" (${source}): stage "${stage}" out of canonical order — chains must follow ${VALID_STAGES.join(" → ")}`);
    }
    seen.add(stage);
    prev = idx;
    validated.push(stage);
  }
  return { name, stages: validated, source };
}
function loadChains() {
  const collected = new Map;
  for (const [name, stages] of Object.entries(BUILTINS)) {
    collected.set(name, { name, stages, source: "builtin" });
  }
  let parsed;
  try {
    parsed = readAnchor();
  } catch {
    die2(`invalid JSON in anchor file ${anchorPath()}`);
  }
  const configured = getProp(parsed, "chains");
  if (configured !== undefined && configured !== null) {
    if (typeof configured !== "object" || Array.isArray(configured)) {
      die2(`"chains" in ${anchorPath()} must be an object mapping chain names to stage lists`);
    }
    for (const [name, stages] of Object.entries(configured)) {
      collected.set(name, { name, stages, source: "anchor" });
    }
  }
  const chains = new Map;
  for (const chain of collected.values())
    chains.set(chain.name, validateChain(chain));
  return chains;
}
var USAGE = "usage: resolve-chain.mjs <chain-name> | --list";
var argv = process.argv.slice(2);
var arg = argv[0];
if (argv.length !== 1 || arg === undefined)
  die2(USAGE);
var chains = loadChains();
if (arg === "--list") {
  out({ chains: [...chains.values()] });
} else if (arg.startsWith("--")) {
  die2(USAGE);
} else {
  const chain = chains.get(arg);
  if (!chain) {
    const available = [...chains.values()].map((c) => `${c.name} (${c.stages.join(", ")})`).join("; ");
    die2(`unknown chain "${arg}" — available chains: ${available}`);
  }
  out(chain);
}
