#!/usr/bin/env node
// GENERATED by tools/build.ts from src/scripts/state.ts — do not edit; rebuild: bun run build
// src/scripts/state.ts
import { existsSync as existsSync3, readFileSync as readFileSync3 } from "node:fs";
import { isAbsolute as isAbsolute2, join as join2, resolve } from "node:path";

// src/lib/anchor.ts
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { isAbsolute, join } from "node:path";
function anchorPath() {
  const home = process.env.HOME || homedir();
  return join(home, ".claude", "strapped.json");
}
function readAnchor() {
  const path = anchorPath();
  if (!existsSync(path))
    return;
  return JSON.parse(readFileSync(path, "utf8"));
}
function getProp(value, key) {
  if (typeof value === "object" && value !== null && key in value) {
    return value[key];
  }
  return;
}
function resolveStateRoot(die) {
  const home = process.env.HOME || homedir();
  let value = null;
  let source = null;
  if (process.env.STRAPPED_STATE_ROOT) {
    value = process.env.STRAPPED_STATE_ROOT;
    source = "$STRAPPED_STATE_ROOT";
  } else {
    const anchor = anchorPath();
    let parsed;
    try {
      parsed = readAnchor();
    } catch {
      die(`invalid JSON in anchor file ${anchor}`);
    }
    const configured = getProp(parsed, "stateRoot");
    if (typeof configured === "string" && configured !== "") {
      value = configured;
      source = anchor;
    }
    if (value === null) {
      value = join(home, ".claude", "strapped");
      source = "default";
    }
  }
  if (value === "~" || value.startsWith("~/"))
    value = home + value.slice(1);
  if (!isAbsolute(value))
    die(`stateRoot is not absolute: "${value}" (from ${source})`);
  return value;
}

// src/lib/cli.ts
function die(prefix, msg) {
  process.stderr.write(`${prefix}: ${msg}
`);
  process.exit(1);
}
function out(obj) {
  process.stdout.write(JSON.stringify(obj) + `
`);
}

// src/lib/frontmatter.ts
import { existsSync as existsSync2, readFileSync as readFileSync2, writeFileSync } from "node:fs";
function splitFrontmatter(src, file, die2) {
  const lines = src.split(`
`);
  if (lines[0] !== "---")
    die2(`${file}: no frontmatter`);
  const end = lines.indexOf("---", 1);
  if (end === -1)
    die2(`${file}: unterminated frontmatter`);
  return { lines, start: 1, end };
}
function parseScalar(raw) {
  const v = raw.trim();
  if (v === "" || v === "null")
    return null;
  if (/^-?\d+$/.test(v))
    return Number(v);
  return v;
}
function parseBracketList(raw) {
  const inner = raw.trim().slice(1, -1).trim();
  return inner === "" ? [] : inner.split(",").map((s) => s.trim());
}
function parseInlineMap(raw) {
  const inner = raw.trim().replace(/^\{/, "").replace(/\}$/, "");
  const parts = [];
  let depth = 0;
  let cur = "";
  for (const ch of inner) {
    if (ch === "[")
      depth++;
    if (ch === "]")
      depth--;
    if (ch === "," && depth === 0) {
      parts.push(cur);
      cur = "";
    } else
      cur += ch;
  }
  if (cur.trim() !== "")
    parts.push(cur);
  const obj = {};
  for (const part of parts) {
    const idx = part.indexOf(":");
    if (idx === -1)
      continue;
    const key = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    obj[key] = value.startsWith("[") ? parseBracketList(value) : parseScalar(value);
  }
  return obj;
}
function parseFrontmatter(src, file, die2) {
  const { lines, start, end } = splitFrontmatter(src, file, die2);
  const fm = {};
  let i = start;
  while (i < end) {
    const m = (lines[i] ?? "").match(/^([A-Za-z_][\w-]*):(.*)$/);
    if (!m || m[1] === undefined) {
      i++;
      continue;
    }
    const key = m[1];
    const rest = (m[2] ?? "").trim();
    if (rest === "") {
      const items = [];
      const map = {};
      let isList = false;
      let isMap = false;
      i++;
      while (i < end && /^\s+\S/.test(lines[i] ?? "")) {
        const line = (lines[i] ?? "").trim();
        if (line.startsWith("- ")) {
          isList = true;
          const body = line.slice(2).trim();
          items.push(body.startsWith("{") ? parseInlineMap(body) : parseScalar(body));
        } else {
          const mm = line.match(/^([\w-]+):\s*(.*)$/);
          if (mm && mm[1] !== undefined) {
            isMap = true;
            map[mm[1]] = parseScalar(mm[2] ?? "");
          }
        }
        i++;
      }
      fm[key] = isList ? items : isMap ? map : null;
      continue;
    }
    fm[key] = rest.startsWith("[") ? parseBracketList(rest) : parseScalar(rest);
    i++;
  }
  return fm;
}
function findFieldLine(lines, start, end, field) {
  for (let i = start;i < end; i++) {
    const line = lines[i];
    if (line === `${field}:` || line !== undefined && line.startsWith(`${field}: `))
      return i;
  }
  return -1;
}
function readField(file, field, die2) {
  if (!existsSync2(file))
    die2(`no such file: ${file}`);
  const src = readFileSync2(file, "utf8");
  const { lines, start, end } = splitFrontmatter(src, file, die2);
  const idx = findFieldLine(lines, start, end, field);
  return { lines, idx, value: idx === -1 ? null : (lines[idx] ?? "").slice(field.length + 1).trim() };
}
function writeField(file, lines, idx, field, value) {
  lines[idx] = `${field}: ${value}`;
  writeFileSync(file, lines.join(`
`));
}

// src/scripts/state.ts
var die2 = (msg) => die("state.mjs", msg);
function mapField(entry, key) {
  if (typeof entry === "object" && entry !== null)
    return entry[key];
  return;
}
function cmdResolve(slug) {
  const stateRoot = resolveStateRoot(die2);
  const runRoot = join2(stateRoot, "runs");
  const runDir = join2(runRoot, slug);
  const manifest = join2(runDir, "manifest.md");
  const base = { slug, stateRoot, runRoot, runDir, manifest };
  if (!existsSync3(manifest)) {
    out({ ...base, exists: false, status: null, seed: null, budgets: null, repos: [] });
    return;
  }
  const fm = parseFrontmatter(readFileSync3(manifest, "utf8"), manifest, die2);
  const repos = (Array.isArray(fm.repos) ? fm.repos : []).map((entry) => {
    const config = join2(stateRoot, "repos", String(mapField(entry, "name")), "config.json");
    const configExists = existsSync3(config);
    let cfg = null;
    if (configExists) {
      try {
        cfg = JSON.parse(readFileSync3(config, "utf8"));
      } catch {
        die2(`invalid JSON in repo config ${config}`);
      }
    }
    return {
      name: mapField(entry, "name") ?? null,
      root: mapField(entry, "root") ?? null,
      config,
      configExists,
      validations: getProp(cfg, "validations") ?? null,
      worktreeRoot: getProp(cfg, "worktreeRoot") ?? null,
      provisioning: getProp(cfg, "provisioning") ?? null
    };
  });
  out({
    ...base,
    exists: true,
    status: fm.status ?? null,
    seed: fm.seed ?? null,
    budgets: fm.budgets ?? null,
    repos
  });
}
var COMPLETE_STATUSES = new Set(["done", "pr-open", "merged"]);
function cmdDag(runDir, only) {
  const manifestFile = join2(runDir, "manifest.md");
  if (!existsSync3(manifestFile))
    die2(`no manifest at ${manifestFile}`);
  const mfm = parseFrontmatter(readFileSync3(manifestFile, "utf8"), manifestFile, die2);
  const list = Array.isArray(mfm.deliverables) ? mfm.deliverables : [];
  if (list.length === 0)
    die2(`manifest has no deliverables list: ${manifestFile}`);
  const nodes = list.map((entry) => {
    const fileField = String(mapField(entry, "file"));
    const file = isAbsolute2(fileField) ? fileField : join2(runDir, fileField);
    if (!existsSync3(file))
      die2(`deliverable file missing: ${file} (listed in manifest as ${mapField(entry, "id")})`);
    const fm = parseFrontmatter(readFileSync3(file, "utf8"), file, die2);
    return {
      id: fm.id ?? mapField(entry, "id"),
      file,
      title: fm.title ?? null,
      status: fm.status ?? null,
      deps: Array.isArray(fm.deps) ? fm.deps : [],
      repo: fm.repo ?? null,
      branch: fm.branch ?? null,
      base: fm.base ?? null,
      worktree: fm.worktree ?? null,
      pr: fm.pr ?? null,
      review_rounds_used: fm.review_rounds_used ?? 0,
      feedback_rounds_used: fm.feedback_rounds_used ?? 0,
      parked_reason: fm.parked_reason ?? null,
      estimated_diff_lines: fm.estimated_diff_lines ?? null
    };
  });
  const byId = new Map(nodes.map((n) => [n.id, n]));
  if (byId.size !== nodes.length)
    die2(`duplicate deliverable ids in ${manifestFile}`);
  for (const n of nodes) {
    for (const dep of n.deps) {
      if (!byId.has(dep))
        die2(`unknown dep ${dep} (referenced by ${n.id})`);
    }
  }
  if (only && !byId.has(only))
    die2(`--only ${only}: no such deliverable`);
  const indegree = new Map(nodes.map((n) => [n.id, n.deps.length]));
  const children = new Map(nodes.map((n) => [n.id, []]));
  for (const n of nodes)
    for (const dep of n.deps)
      (children.get(dep) ?? []).push(n.id);
  const queue = nodes.filter((n) => n.deps.length === 0).map((n) => n.id);
  const topo = [];
  while (queue.length > 0) {
    queue.sort();
    const id = queue.shift();
    topo.push(id);
    for (const child of children.get(id) ?? []) {
      indegree.set(child, (indegree.get(child) ?? 0) - 1);
      if (indegree.get(child) === 0)
        queue.push(child);
    }
  }
  if (topo.length !== nodes.length) {
    const stuck = nodes.map((n) => n.id).filter((id) => !topo.includes(id)).sort();
    die2(`dependency cycle involving: ${stuck.join(", ")}`);
  }
  const complete = (id) => COMPLETE_STATUSES.has(byId.get(id)?.status ?? null);
  const depsMet = (n) => n.deps.every(complete);
  let ready = nodes.filter((n) => n.status === "pending" && depsMet(n)).map((n) => n.id);
  if (only) {
    const node = byId.get(only);
    const resumable = node !== undefined && (node.status === "parked" || node.status === "in-progress");
    if (node !== undefined && resumable && depsMet(node) && !ready.includes(only))
      ready.push(only);
    ready = ready.filter((id) => id === only);
  }
  ready.sort();
  const blocked = nodes.filter((n) => n.status === "pending" && !depsMet(n)).map((n) => ({ id: n.id, blockedOn: n.deps.filter((dep) => !complete(dep)) }));
  const remaining = nodes.filter((n) => !COMPLETE_STATUSES.has(n.status)).length;
  out({
    manifest: { status: mfm.status ?? null, seed: mfm.seed ?? null, budgets: mfm.budgets ?? null },
    nodes,
    ready,
    topo,
    blocked,
    remaining
  });
}
function cmdSet(file, field, value) {
  if (/[\r\n]/.test(value))
    die2("value must be a single line");
  const { lines, idx, value: old } = readField(file, field, die2);
  if (idx === -1)
    die2(`unknown frontmatter field "${field}" in ${file}`);
  if (lines[idx] !== `${field}: ${value}`)
    writeField(file, lines, idx, field, value);
  out({ file, field, old, new: value });
}
var DELIVERABLE_EDGES = new Set([
  "pending>in-progress",
  "parked>in-progress",
  "in-progress>done",
  "in-progress>parked",
  "fixing>parked",
  "in-review>parked",
  "done>parked",
  "pr-open>parked",
  "done>pr-open",
  "pr-open>merged",
  "pr-open>fixing",
  "fixing>in-review",
  "in-review>fixing",
  "in-review>pr-open",
  "in-review>done"
]);
function cmdTransition(file, to, from) {
  const { lines, idx, value: current } = readField(file, "status", die2);
  if (idx === -1)
    die2(`no status field in ${file}`);
  if (from !== null && current !== from) {
    die2(`expected status "${from}" but found "${current}" in ${file}`);
  }
  if (current === to) {
    out({ file, from: current, to, changed: false });
    return;
  }
  if (!DELIVERABLE_EDGES.has(`${current}>${to}`)) {
    die2(`illegal transition ${current} → ${to} for ${file}`);
  }
  writeField(file, lines, idx, "status", to);
  out({ file, from: current, to, changed: true });
}
var MANIFEST_LADDER = ["draft", "in-review", "approved", "implementing", "complete"];
function cmdManifestStatus(runDir, to) {
  const file = join2(runDir, "manifest.md");
  if (!existsSync3(file))
    die2(`no manifest at ${file}`);
  const { lines, idx, value: current } = readField(file, "status", die2);
  if (idx === -1)
    die2(`no status field in ${file}`);
  const toIdx = MANIFEST_LADDER.indexOf(to);
  if (toIdx === -1)
    die2(`unknown manifest status "${to}"`);
  const currentIdx = current === null ? -1 : MANIFEST_LADDER.indexOf(current);
  if (currentIdx === -1)
    die2(`manifest has unknown status "${current}" in ${file}`);
  if (current === to) {
    out({ file, from: current, to, changed: false });
    return;
  }
  if (toIdx < currentIdx)
    die2(`manifest status is forward-only: ${current} → ${to} rejected`);
  writeField(file, lines, idx, "status", to);
  out({ file, from: current, to, changed: true });
}
var USAGE = "usage: state.mjs <resolve|dag|set|transition|manifest-status> ...";
var [cmd, ...rest] = process.argv.slice(2);
function takeFlag(args, flag) {
  const i = args.indexOf(flag);
  if (i === -1)
    return null;
  const value = args[i + 1];
  if (!value)
    die2(`${flag} requires a value`);
  args.splice(i, 2);
  return value;
}
switch (cmd) {
  case "resolve": {
    const slug = rest[0];
    if (!slug)
      die2("usage: state.mjs resolve <slug>");
    cmdResolve(slug);
    break;
  }
  case "dag": {
    const only = takeFlag(rest, "--only");
    const runDirArg = rest[0];
    if (!runDirArg)
      die2("usage: state.mjs dag <runDir> [--only <Did>]");
    cmdDag(resolve(runDirArg), only);
    break;
  }
  case "set": {
    const fileArg = rest[0];
    const fieldArg = rest[1];
    if (rest.length < 3 || fileArg === undefined || fieldArg === undefined) {
      die2("usage: state.mjs set <file> <field> <value>");
    }
    cmdSet(resolve(fileArg), fieldArg, rest.slice(2).join(" "));
    break;
  }
  case "transition": {
    const from = takeFlag(rest, "--from");
    const fileArg = rest[0];
    const toArg = rest[1];
    if (!fileArg || !toArg)
      die2("usage: state.mjs transition <file> <to> [--from <expected>]");
    cmdTransition(resolve(fileArg), toArg, from);
    break;
  }
  case "manifest-status": {
    const runDirArg = rest[0];
    const toArg = rest[1];
    if (!runDirArg || !toArg)
      die2("usage: state.mjs manifest-status <runDir> <to>");
    cmdManifestStatus(resolve(runDirArg), toArg);
    break;
  }
  default:
    die2(USAGE);
}
