// GENERATED by tools/build.ts from src/workflows/strapped-run/main.ts — do not edit; rebuild: bun run build
export const meta = {
  name: 'strapped-run',
  description: 'The strapped mono-workflow: every orchestration loop (plan + adversarial plan review, DAG implement waves with bounded code review, stacked-PR create) lives here as plain stage functions selected by args.stages. Zero workflow() calls anywhere, so the harness one-level nesting limit never engages. The standalone skills dispatch this same file with singleton stage lists.',
  phases: [
    {
      title: 'plan',
      detail: 'planner writes research/manifest/deliverables, then the bounded adversarial plan-review loop',
    },
    {
      title: 'implement',
      detail: 'DAG wave loop: coordinator executor per pass, fresh implementer per node, bounded code-review/fix rounds, outcome applier',
    },
    {
      title: 'pr',
      detail: 'stacked-PR create pass, gated on every node being done-or-later',
    },
  ],
}

// src/workflows/strapped-run/config.ts
var STAGE_ORDER = ["plan", "implement", "pr"];
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function requireString(rec, key) {
  const value = rec[key];
  if (typeof value !== "string")
    throw new Error(`config field "${key}" must be a string`);
  return value;
}
function requireNumber(rec, key) {
  const value = rec[key];
  if (typeof value !== "number")
    throw new Error(`config field "${key}" must be a number`);
  return value;
}
function parseResearchRounds(value) {
  if (value === undefined)
    return 2;
  if (typeof value !== "number" || value < 1) {
    throw new Error('config field "researchRounds" must be a number >= 1');
  }
  return value;
}
function parseStages(value) {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`stages must be a non-empty ordered subset of [${STAGE_ORDER.join(", ")}]`);
  }
  const list = value;
  const stages = [];
  const seenStages = new Set;
  let prevIndex = -1;
  for (const name of list) {
    const index = STAGE_ORDER.findIndex((s) => s === name);
    const stage = index === -1 ? undefined : STAGE_ORDER[index];
    if (stage === undefined)
      throw new Error(`unknown stage "${name}" — canonical stages: ${STAGE_ORDER.join(", ")}`);
    if (seenStages.has(stage))
      throw new Error(`duplicate stage "${stage}"`);
    if (index < prevIndex)
      throw new Error(`stages out of canonical order at "${stage}" — canonical order: ${STAGE_ORDER.join(", ")}`);
    seenStages.add(stage);
    prevIndex = index;
    stages.push(stage);
  }
  return stages;
}
function parseScripts(value) {
  if (value === undefined || value === null)
    return {};
  if (!isRecord(value))
    throw new Error('config field "scripts" must be an object');
  const scripts = {};
  if (typeof value.state === "string")
    scripts.state = value.state;
  if (typeof value.worktree === "string")
    scripts.worktree = value.worktree;
  return scripts;
}
function parseRules(value, where) {
  if (!Array.isArray(value))
    throw new Error(`config: ${where} must be an array of rule ids`);
  const list = value;
  return list.map((rule, i) => {
    if (typeof rule !== "string" || rule.length === 0) {
      throw new Error(`config: ${where}[${i}] must be a rule id string (rule text lives in rulesFile, never in args)`);
    }
    return rule;
  });
}
function parseRulesByRound(value) {
  if (!Array.isArray(value))
    throw new Error('config field "rulesByRound" must be an array');
  const list = value;
  return list.map((entry, i) => {
    if (!isRecord(entry))
      throw new Error(`config: rulesByRound[${i}] must be a { a, b } rule partition`);
    return { a: parseRules(entry.a, `rulesByRound[${i}].a`), b: parseRules(entry.b, `rulesByRound[${i}].b`) };
  });
}
function parseRulesFile(value, rulesByRound) {
  if (typeof value === "string" && value.length > 0)
    return value;
  if (value !== undefined && value !== null)
    throw new Error('config field "rulesFile" must be a string');
  if (rulesByRound.length > 0) {
    throw new Error('config field "rulesFile" (absolute path to reviews/rules-snapshot.md) is required when "rulesByRound" is non-empty — review agents read the rule text from it');
  }
  return null;
}
function parseRepos(value, where) {
  if (!Array.isArray(value))
    throw new Error(`config: ${where} must be an array of repos`);
  const list = value;
  return list.map((repo, i) => {
    if (!isRecord(repo) || typeof repo.name !== "string" || typeof repo.root !== "string") {
      throw new Error(`config: ${where}[${i}] must be a repo { name, root }`);
    }
    return { name: repo.name, root: repo.root };
  });
}
function parsePlanArgs(value) {
  if (!isRecord(value))
    throw new Error("config: stageArgs.plan must be an object");
  const parsed = {};
  if (value.sourcePlan !== undefined) {
    if (typeof value.sourcePlan !== "string")
      throw new Error("config: stageArgs.plan.sourcePlan must be a string");
    parsed.sourcePlan = value.sourcePlan;
  }
  if (value.repos !== undefined)
    parsed.repos = parseRepos(value.repos, "stageArgs.plan.repos");
  return parsed;
}
function parseImplementArgs(value) {
  if (!isRecord(value))
    throw new Error("config: stageArgs.implement must be an object");
  const parsed = {};
  if (value.only !== undefined && value.only !== null) {
    if (typeof value.only !== "string")
      throw new Error("config: stageArgs.implement.only must be a string");
    parsed.only = value.only;
  }
  return parsed;
}
function parsePrArgs(value) {
  if (!isRecord(value))
    throw new Error("config: stageArgs.pr must be an object");
  const parsed = {};
  if (value.dryRun !== undefined) {
    if (typeof value.dryRun !== "boolean")
      throw new Error("config: stageArgs.pr.dryRun must be a boolean");
    parsed.dryRun = value.dryRun;
  }
  return parsed;
}
function parseStageArgsMap(value) {
  if (value === undefined || value === null)
    return {};
  if (!isRecord(value))
    throw new Error('config field "stageArgs" must be an object');
  const parsed = {};
  if (value.plan !== undefined)
    parsed.plan = parsePlanArgs(value.plan);
  if (value.implement !== undefined)
    parsed.implement = parseImplementArgs(value.implement);
  if (value.pr !== undefined)
    parsed.pr = parsePrArgs(value.pr);
  return parsed;
}
function parseConfig(raw) {
  const parsed = typeof raw === "string" ? JSON.parse(raw) : raw;
  if (!isRecord(parsed))
    throw new Error("config must be an object or its JSON string");
  const stages = parseStages(parsed.stages);
  const rulesByRound = parsed.rulesByRound === undefined ? [] : parseRulesByRound(parsed.rulesByRound);
  return {
    slug: requireString(parsed, "slug"),
    dir: requireString(parsed, "dir"),
    conventionsFile: requireString(parsed, "conventionsFile"),
    scripts: parseScripts(parsed.scripts),
    seed: requireNumber(parsed, "seed"),
    confidenceMin: requireNumber(parsed, "confidenceMin"),
    planRounds: requireNumber(parsed, "planRounds"),
    codeRounds: requireNumber(parsed, "codeRounds"),
    researchRounds: parseResearchRounds(parsed.researchRounds),
    rulesByRound,
    rulesFile: parseRulesFile(parsed.rulesFile, rulesByRound),
    stages,
    stageArgs: parseStageArgsMap(parsed.stageArgs)
  };
}
function stageArgsFor(cfg, name) {
  return cfg.stageArgs[name] || {};
}
function rulesForRound(cfg, round) {
  const rules = cfg.rulesByRound[round - 1];
  if (!rules)
    throw new Error(`rulesByRound has no entry for round ${round}`);
  return rules;
}
function rulesFileFor(cfg) {
  if (cfg.rulesFile === null)
    throw new Error('config field "rulesFile" is required to run review rounds');
  return cfg.rulesFile;
}
function repoList(repos) {
  if (!repos || !repos.length)
    return "(no target repos supplied)";
  return repos.map((r) => `- ${r.name} → ${r.root}`).join(`
`);
}

// src/workflows/strapped-run/schemas.generated.ts
var PLAN_SCHEMA = {
  type: "object",
  properties: {
    deliverables: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string"
          },
          file: {
            type: "string"
          },
          title: {
            type: "string"
          },
          deps: {
            type: "array",
            items: {
              type: "string"
            }
          }
        },
        required: [
          "id",
          "file",
          "title",
          "deps"
        ],
        additionalProperties: false
      }
    },
    summary: {
      type: "string"
    }
  },
  required: [
    "deliverables",
    "summary"
  ],
  additionalProperties: false
};
var FINDINGS_SCHEMA = {
  type: "object",
  properties: {
    findings: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string"
          },
          key: {
            type: "string",
            description: "<rule-id-or-gap>:<location>, stable across rounds for dedup"
          },
          rule: {
            type: [
              "string",
              "null"
            ]
          },
          severity: {
            type: "string",
            enum: [
              "blocking",
              "concern",
              "suggestion"
            ]
          },
          location: {
            type: "string"
          },
          what: {
            type: "string"
          },
          why: {
            type: "string"
          },
          evidence: {
            type: "string"
          },
          confidence: {
            type: "number",
            minimum: 0,
            maximum: 100
          },
          recommendation: {
            type: "string"
          }
        },
        required: [
          "id",
          "key",
          "rule",
          "severity",
          "location",
          "what",
          "why",
          "evidence",
          "confidence",
          "recommendation"
        ],
        additionalProperties: false
      }
    },
    rule_checklist: {
      type: "array",
      items: {
        type: "object",
        properties: {
          rule: {
            type: "string"
          },
          verdict: {
            type: "string",
            enum: [
              "pass",
              "violation",
              "na"
            ]
          },
          evidence: {
            type: "string"
          }
        },
        required: [
          "rule",
          "verdict",
          "evidence"
        ],
        additionalProperties: false
      }
    },
    ac_checklist: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string"
          },
          verdict: {
            type: "string",
            enum: [
              "pass",
              "violation",
              "na"
            ]
          },
          evidence: {
            type: "string"
          }
        },
        required: [
          "id",
          "verdict",
          "evidence"
        ],
        additionalProperties: false,
        description: "One reviewer verdict on a single enumerated acceptance-criterion item. Kept as its OWN required list (not folded into `rule_checklist`) so a reviewer can never silently omit the per-item AC verdicts: a required, separate field is enforced by the structured-output schema every round, giving ACs the same weight as guideline rules."
      },
      description: "Per-item AC verdicts — required (may be empty when the artifact has no enumerated section)."
    }
  },
  required: [
    "findings",
    "rule_checklist",
    "ac_checklist"
  ],
  additionalProperties: false
};
var VERIFY_SCHEMA = {
  type: "object",
  properties: {
    verdicts: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string",
            description: "The adjudicated finding's id."
          },
          verdict: {
            type: "string",
            enum: [
              "confirmed",
              "plausible",
              "refuted"
            ]
          },
          confidence: {
            type: "number",
            minimum: 0,
            maximum: 100
          },
          evidence: {
            type: "string"
          }
        },
        required: [
          "id",
          "verdict",
          "confidence",
          "evidence"
        ],
        additionalProperties: false,
        description: "One per-finding verdict cast by the verify-consolidate agent."
      },
      description: "One verdict per gating finding adjudicated this round."
    },
    new_confirmed_ids: {
      type: "array",
      items: {
        type: "string"
      }
    },
    duplicate_ids: {
      type: "array",
      items: {
        type: "string"
      }
    }
  },
  required: [
    "verdicts",
    "new_confirmed_ids",
    "duplicate_ids"
  ],
  additionalProperties: false
};
var IMPLEMENT_SCHEMA = {
  type: "object",
  properties: {
    status: {
      type: "string",
      enum: [
        "implemented",
        "blocked"
      ]
    },
    summary: {
      type: "string"
    },
    validations_green: {
      type: "boolean"
    },
    blocker: {
      type: [
        "string",
        "null"
      ]
    }
  },
  required: [
    "status",
    "summary",
    "validations_green",
    "blocker"
  ],
  additionalProperties: false
};
var WAVE_SCHEMA = {
  type: "object",
  properties: {
    items: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string"
          },
          repo: {
            type: "string"
          },
          repoRoot: {
            type: "string"
          },
          validations: {
            type: "array",
            items: {
              type: "string"
            }
          },
          planFile: {
            type: "string"
          },
          worktree: {
            type: "string"
          },
          branch: {
            type: "string"
          },
          base: {
            type: "string"
          },
          resumeNote: {
            type: [
              "string",
              "null"
            ]
          },
          pr: {
            type: [
              "string",
              "null"
            ],
            description: "the node's `pr:` frontmatter URL, null for a pre-PR node"
          }
        },
        required: [
          "id",
          "repo",
          "repoRoot",
          "validations",
          "planFile",
          "worktree",
          "branch",
          "base",
          "resumeNote",
          "pr"
        ],
        additionalProperties: false
      }
    },
    dag: {
      type: "object",
      properties: {
        ready: {
          type: "array",
          items: {
            type: "string"
          }
        },
        resumable: {
          type: "array",
          items: {
            type: "string"
          },
          description: "In-progress node ids from the dag's nodes list — interrupted implementations this pass may resume."
        },
        remaining: {
          type: "number"
        },
        blocked: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string"
              },
              blockedOn: {
                type: "array",
                items: {
                  type: "string"
                }
              }
            },
            required: [
              "id",
              "blockedOn"
            ],
            additionalProperties: false
          }
        }
      },
      required: [
        "ready",
        "resumable",
        "remaining",
        "blocked"
      ],
      additionalProperties: false,
      description: "The workflow trusts this paste: `remaining`/`blocked` are read from here verbatim."
    }
  },
  required: [
    "items",
    "dag"
  ],
  additionalProperties: false
};
var APPLY_SCHEMA = {
  type: "object",
  properties: {
    applied: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string"
          },
          status: {
            type: "string",
            enum: [
              "done",
              "parked",
              "pr-open"
            ]
          }
        },
        required: [
          "id",
          "status"
        ],
        additionalProperties: false
      }
    }
  },
  required: [
    "applied"
  ],
  additionalProperties: false
};
var APPROVE_SCHEMA = {
  type: "object",
  properties: {
    changed: {
      type: "boolean"
    }
  },
  required: [
    "changed"
  ],
  additionalProperties: false
};
var PROBE_SCHEMA = {
  type: "object",
  properties: {
    remaining: {
      type: "number"
    },
    notDone: {
      type: "array",
      items: {
        type: "string"
      }
    }
  },
  required: [
    "remaining",
    "notDone"
  ],
  additionalProperties: false
};
var PR_SCHEMA = {
  type: "object",
  properties: {
    prs: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string"
          },
          url: {
            type: [
              "string",
              "null"
            ]
          },
          skipped: {
            type: "boolean"
          },
          reason: {
            type: [
              "string",
              "null"
            ]
          }
        },
        required: [
          "id",
          "url",
          "skipped",
          "reason"
        ],
        additionalProperties: false
      }
    },
    summary: {
      type: "string"
    }
  },
  required: [
    "prs",
    "summary"
  ],
  additionalProperties: false
};
var PLAN_LEAD_SCHEMA = {
  type: "object",
  properties: {
    deliverables: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string"
          },
          file: {
            type: "string"
          },
          title: {
            type: "string"
          },
          deps: {
            type: "array",
            items: {
              type: "string"
            }
          }
        },
        required: [
          "id",
          "file",
          "title",
          "deps"
        ],
        additionalProperties: false
      }
    },
    summary: {
      type: "string"
    },
    research_requests: {
      type: "array",
      items: {
        type: "object",
        properties: {
          topic: {
            type: "string"
          },
          brief: {
            type: "string"
          }
        },
        required: [
          "topic",
          "brief"
        ],
        additionalProperties: false,
        description: "One research topic a planner or researcher enqueues for a later BFS round."
      },
      description: "Empty = the small-ask exit: the planner already wrote every plan artifact itself."
    }
  },
  required: [
    "deliverables",
    "summary",
    "research_requests"
  ],
  additionalProperties: false
};
var RESEARCH_SCHEMA = {
  type: "object",
  properties: {
    topic: {
      type: "string"
    },
    notes_file: {
      type: "string"
    },
    summary: {
      type: "string"
    },
    research_requests: {
      type: "array",
      items: {
        type: "object",
        properties: {
          topic: {
            type: "string"
          },
          brief: {
            type: "string"
          }
        },
        required: [
          "topic",
          "brief"
        ],
        additionalProperties: false,
        description: "One research topic a planner or researcher enqueues for a later BFS round."
      }
    }
  },
  required: [
    "topic",
    "notes_file",
    "summary",
    "research_requests"
  ],
  additionalProperties: false
};
var RESEARCH_FINAL_SCHEMA = {
  type: "object",
  properties: {
    topic: {
      type: "string"
    },
    notes_file: {
      type: "string"
    },
    summary: {
      type: "string"
    }
  },
  required: [
    "topic",
    "notes_file",
    "summary"
  ],
  additionalProperties: false
};

// src/workflows/strapped-run/review-loop.ts
var PLAN_LENSES = {
  a: "completeness: is every element of the original ask covered by some deliverable? Hunt for missing requirements, unhandled edge cases, acceptance criteria without tests, and parts of the ask that silently disappeared",
  b: "soundness: wrong assumptions about the codebase, DAG dependency errors (missing or backwards deps, undeclared cross-deliverable coupling), deliverables that mix unrelated themes or whose estimated meaningful diff (excluding generated code, dependency bumps, and fixtures) exceeds ~1,000 lines and should be split, deliverables/chains that should be CONSOLIDATED (fragments of one theme, or a linear chain whose combined meaningful diff — excluding generated code, dependency bumps, and fixtures — is under the ~1,000-line threshold and could be a single deliverable/PR), planned work that is dead, duplicated, or superseded within the plan (steps or files a later step obviates, two deliverables doing the same work, or acceptance criteria/tests no remaining step produces), and steps that cannot work as written"
};
function digest(seen) {
  if (!seen.length)
    return "(none — first round)";
  return seen.map((f) => `- [${f.severity}] ${f.key}: ${f.what} (round ${f.round}, ${f.status})`).join(`
`);
}
async function runReviewLoop(cfg, opts) {
  const maxRounds = opts.maxRounds;
  if (maxRounds === 0) {
    log("review budget 0 — skipping adversarial review");
    return { converged: true, rounds: 0, outstanding: [] };
  }
  const artifactNounCap = opts.artifactNoun.charAt(0).toUpperCase() + opts.artifactNoun.slice(1);
  const rulesFile = rulesFileFor(cfg);
  function reviewerPrompt(which, rules, seen2, round) {
    return `You are an adversarial plan reviewer with fresh context. Your job is to find real gaps between ${opts.artifactDescription} and the original ask, before any code is written.

Original ask: ${opts.ask}
${artifactNounCap} under review, in ${cfg.dir}: ${opts.artifactLocation}.
Conventions the plan must follow: ${cfg.conventionsFile}
Target repos (explore any of these as needed to check the plan's claims against reality):
${repoList(opts.repos)}

Read the original ask first, then the whole ${opts.artifactNoun}, then verify claims against the actual codebase(s) where they matter.

Your lens (your main hunting ground beyond the rules): ${PLAN_LENSES[which]}.
${which === "b" ? `
Soundness — multi-repo checks specific to this run: verify each deliverable has a \`repo:\` field naming one of the target repos above; verify each deliverable's \`base:\` obeys the cross-repo base rule (it is a branch in the SAME repo as the deliverable, or that repo's \`main\` for roots and for cross-repo children — a deliverable can never base on a branch in a different repo); and verify that any child depending on work that must first land through some external step outside this run's control (e.g. a cross-repo parent's output becoming available in the child's repo) DECLARES that prerequisite under a \`## Preconditions\` section in its body — such dependencies are legitimate DAG nodes that park at implement time when the precondition is unmet, so flag a MISSING declaration, never the dependency itself.
` : ""}
Your assigned guideline rules — you are the ONLY reviewer checking the plan against these, so check every one explicitly (does the plan instruct or imply work that would violate the rule?): ${rules.join(", ")}.
These ids are your whole assignment, but they carry no text here: before reviewing, Read the rules snapshot at ${rulesFile} for each assigned rule's verbatim text (one \`- <id> (<source>): <text>\` line per rule; ignore the ids not assigned to you).

Known findings from earlier rounds — do NOT re-report unless the revision failed to address them:
${digest(seen2)}

Enumerated AC checklist — you and the other reviewer BOTH return this every round (it is NOT partitioned like the guideline rules): read EVERY artifact file's \`## Acceptance criteria\` section, enumerate each item in order as AC1..ACn across the whole artifact, and return one ac_checklist entry per item ({ id: "AC<k>", verdict: pass|violation|na, evidence: one line }). An item the ${opts.artifactNoun} fails to satisfy, or that no step/test covers, is a BLOCKING finding carrying full guideline-rule weight — enumerating and checking these items is as load-bearing as the rule checklist. If no file has a \`## Acceptance criteria\` section, return \`ac_checklist: []\`.

Severity: "blocking" = the plan as written produces wrong or missing work; "concern" = likely gap needing a fix or an explicit justification; "suggestion" = optional polish (never drives revision). Stable key format "<rule-id-or-gap>:<plan-location>". Confidence under ${cfg.confidenceMin} will be dropped.

You MUST return a rule_checklist verdict (pass/violation/na + one line of evidence) for every assigned rule (${rules.join(", ")}), the ac_checklist covering every AC item, plus your findings. Round: ${round}.`;
  }
  const seen = [];
  let converged = false;
  let roundsUsed = 0;
  let outstanding = [];
  async function runReviewRound(round, confirmation) {
    const rules = rulesForRound(cfg, round);
    const seedUsed = cfg.seed + round;
    const roundLabel = confirmation ? `${round}-confirm` : `${round}`;
    const phaseLabel = confirmation ? `Confirm ${round}` : `Review ${round}`;
    phase(phaseLabel);
    const reviews = await parallel([
      () => agent(reviewerPrompt("a", rules.a, seen, round), { label: `plan-review:a:r${roundLabel}`, schema: FINDINGS_SCHEMA }),
      () => agent(reviewerPrompt("b", rules.b, seen, round), { label: `plan-review:b:r${roundLabel}`, schema: FINDINGS_SCHEMA })
    ]);
    const tagged = reviews.map((r, i) => ({ r, which: i === 0 ? "a" : "b" })).filter((x) => Boolean(x.r));
    const allFindings = tagged.flatMap((x) => x.r.findings.map((f) => ({ ...f, id: `r${roundLabel}-${x.which}-${f.id}` })));
    const checklists = Object.fromEntries(tagged.map((x) => [x.which, x.r.rule_checklist]));
    const acChecklists = Object.fromEntries(tagged.map((x) => [x.which, x.r.ac_checklist]));
    const gating = allFindings.filter((f) => f.severity !== "suggestion");
    const suggestions = allFindings.filter((f) => f.severity === "suggestion");
    log(`round ${roundLabel}: ${gating.length} gating finding(s), ${suggestions.length} suggestion(s)`);
    const roundFile = `${cfg.dir}/reviews/${opts.roundFilePrefix}-${roundLabel}.md`;
    const verification = await agent(gating.length === 0 ? `You are the record-writer for round ${roundLabel} of strapped run "${cfg.slug}". This round is CLEAN: the reviewers returned zero gating findings, so there is nothing to adjudicate and nothing to dedup. Do NOT re-review ${opts.verifyArtifactPhrase} and do NOT read the ${opts.artifactNoun} files — your only job is the round record. Round-record format: ${cfg.conventionsFile}.

Write ${roundFile} with frontmatter (round: ${roundLabel}, seed_used: ${seedUsed}, reviewer_a_rules: ${JSON.stringify(rules.a)}, reviewer_b_rules: ${JSON.stringify(rules.b)}, new_confirmed: 0, outcome: converged, findings list = the suggestions below with status suggestion) and a body carrying the suggestions plus both rule checklists AND both AC/addendum checklists verbatim.

Suggestions (non-gating, record only):
${JSON.stringify(suggestions, null, 2)}

Rule checklists: ${JSON.stringify(checklists, null, 2)}

AC/addendum checklists: ${JSON.stringify(acChecklists, null, 2)}

Return empty verdicts, empty new-confirmed ids, and empty duplicate ids.` : `You are the verify-consolidate agent for round ${roundLabel} of strapped run "${cfg.slug}": a skeptical verifier adjudicating EVERY gating finding in one batch pass, then the round's consolidator writing its record. Round-record format: ${cfg.conventionsFile}.${confirmation ? `
This is a CONFIRMATION pass after the final budgeted round: its findings were all fixed, and this pass re-checks whether any NEW gap remains.` : ""}

Plan reviewers claim the following gaps in ${opts.verifyArtifactPhrase} at ${cfg.dir} (original ask: ${opts.ask}). Target repos you may explore to check each claim:
${repoList(opts.repos)}

The guideline rules behind rule-keyed findings and the checklists carry only their ids here — the verbatim rule text lives in the rules snapshot at ${rulesFile}; Read it whenever a rule's wording matters to a verdict.

Gating findings to adjudicate:
${JSON.stringify(gating, null, 2)}

Verification stance, applied to each finding independently: it is NOT a real gap unless the documents prove otherwise. Read the ask and the ${opts.artifactNoun} files yourself — a claimed-missing item may be covered elsewhere in the ${opts.artifactNoun}, the assumption may actually hold in the codebase, or the claim may misread the ask. Cast one verdict per finding id — "confirmed" (the gap is proven real), "plausible" (credible but unproven), or "refuted" (not a real gap) — with a corrected confidence (0-100) that the gap is real and one line of evidence. A finding with verdict refuted, or confidence below ${cfg.confidenceMin}, does not survive.

Suggestions (non-gating, never verified, record only):
${JSON.stringify(suggestions, null, 2)}

Rule checklists: ${JSON.stringify(checklists, null, 2)}

AC/addendum checklists (per-item AC pass/violation/na verdicts from each reviewer): ${JSON.stringify(acChecklists, null, 2)}

Seen digest from prior rounds:
${digest(seen)}

Prior round files live at ${cfg.dir}/reviews/${opts.roundFilePrefix}-*.md — read them.

Consolidation tasks, over the findings that survive your verdicts:
1. Merge same-root-cause findings by key against this round's set and all prior rounds; a match on a prior key is a duplicate unless the prior record marks it fixed and the revision regressed.
2. Write ${roundFile} with frontmatter (round: ${roundLabel}, seed_used: ${seedUsed}, reviewer_a_rules: ${JSON.stringify(rules.a)}, reviewer_b_rules: ${JSON.stringify(rules.b)}, new_confirmed: <count>, outcome: converged if zero new confirmed else revise, findings list with one entry per finding carrying { id, key, severity, verdict: confirmed|plausible|refuted, confidence, status: open|refuted|duplicate } per the conventions) and full finding bodies plus both rule checklists AND both AC/addendum checklists (the per-item AC pass/violation/na verdicts).
3. Return your per-finding verdicts, the ids of truly-NEW confirmed findings (surviving and not duplicates), and the duplicate ids.`, { label: `verify:r${roundLabel}`, phase: phaseLabel, effort: "low", schema: VERIFY_SCHEMA });
    if (!verification) {
      if (gating.length)
        log(`round ${roundLabel}: verifier cast no vote — ${gating.length} gating finding(s) excluded`);
      return { newConfirmed: [], newIds: new Set, roundFile };
    }
    const verdictById = new Map(verification.verdicts.map((v) => [v.id, v]));
    const noVote = gating.filter((f) => !verdictById.has(f.id));
    if (noVote.length)
      log(`round ${roundLabel}: verifier cast no vote on ${noVote.length} finding(s) — excluded`);
    const surviving = gating.filter((f) => {
      const v = verdictById.get(f.id);
      return v !== undefined && v.verdict !== "refuted" && v.confidence >= cfg.confidenceMin;
    });
    const newIds = new Set(verification.new_confirmed_ids);
    const newConfirmed = surviving.filter((f) => newIds.has(f.id));
    log(`round ${roundLabel}: ${newConfirmed.length} NEW confirmed finding(s)`);
    return { newConfirmed, newIds: new Set(newConfirmed.map((f) => f.id)), roundFile };
  }
  let lastRoundFixedAll = false;
  let revisionFailed = false;
  for (let round = 1;round <= maxRounds; round++) {
    roundsUsed = round;
    lastRoundFixedAll = false;
    const { newConfirmed, newIds, roundFile } = await runReviewRound(round, false);
    for (const f of newConfirmed)
      seen.push({ ...f, round, status: "open" });
    if (newConfirmed.length === 0) {
      converged = true;
      outstanding = [];
      break;
    }
    outstanding = newConfirmed;
    phase(`Revise ${round}`);
    const revision = await agent(opts.reviserPromptFn(newConfirmed, roundFile), { label: `revise:r${round}`, phase: `Revise ${round}` });
    if (revision) {
      for (const f of seen)
        if (newIds.has(f.id))
          f.status = "fixed";
      lastRoundFixedAll = true;
    } else {
      revisionFailed = true;
      break;
    }
  }
  if (!converged && !revisionFailed && lastRoundFixedAll) {
    const { newConfirmed } = await runReviewRound(maxRounds, true);
    for (const f of newConfirmed)
      seen.push({ ...f, round: maxRounds, status: "open" });
    if (newConfirmed.length === 0) {
      converged = true;
      outstanding = [];
    }
  }
  if (!converged) {
    outstanding = seen.filter((f) => f.status === "open");
  }
  return {
    converged,
    rounds: roundsUsed,
    outstanding: outstanding.map((f) => ({ id: f.id, key: f.key, severity: f.severity, what: f.what }))
  };
}

// src/workflows/strapped-run/stages/implement-review.ts
var CODE_LENSES = {
  a: "correctness: logic bugs, unhandled edge cases, race conditions, broken error paths, and acceptance-criteria compliance",
  b: "convention and test fidelity plus dead-code hygiene: adherence to the assigned guidelines, and test quality — integration-style tests of public interfaces, no mocking, aiohttp test servers for network, polyfactory for stubs; AND dead/duplicated/superseded code — leftover or unreachable code, tests or fixtures orphaned by a changed idea (kept after the code they covered was rewritten or removed), and code no acceptance criterion or addendum task needs"
};
async function runCodeReviewRound(cfg, { item, round, confirmation, seen }) {
  const rules = rulesForRound(cfg, round);
  const rulesFile = rulesFileFor(cfg);
  const roundLabel = confirmation ? `${round}-confirm` : `${round}`;
  const seedUsed = cfg.seed + round;
  const seenDigest = seen.length ? digest(seen) : "";
  function reviewerPrompt(which) {
    return `You are an adversarial code reviewer with fresh context. Review exactly one deliverable's implementation.

Deliverable: ${item.id} of strapped run "${cfg.slug}".
Worktree (the code under review lives here): ${item.worktree}${item.repo ? `
Target repo: ${item.repo}${item.repoRoot ? ` (root ${item.repoRoot})` : ""}` : ""}
Branch: ${item.branch}   Base: ${item.base}

Procedure:
1. Read the rules snapshot at ${rulesFile} for the verbatim text of your assigned guideline rules (${rules[which].join(", ")}) — the workflow args carry only their ids; each rule is a \`- <id> (<source>): <text>\` line, and the ids not assigned to you are the other reviewer's.
2. Read the deliverable plan at ${item.planFile} — its acceptance criteria define what the code must do. Enumerate every item under its \`## Acceptance criteria\` as AC1..ACn — and, if the plan ALSO carries a \`## Feedback addendum\` section, every addendum task under it too, continuing the numbering — and return one ac_checklist entry per item ({ id: "AC<k>", verdict: pass|violation|na, evidence: one line pointing at the code/test that satisfies or fails it }). An AC or addendum item the CODE fails to satisfy or leaves untested is a BLOCKING finding. This checks the actual code, not just the plan. A plan with neither section → \`ac_checklist: []\`.
3. In the worktree, run: git diff ${item.base}...${item.branch}
4. Read every touched file in full in the worktree, plus any callers or tests you need for context.
${item.validations && item.validations.length ? `
This repo's validations (must be green for the deliverable — assume the implementer ran them; flag any code that would break one):
${item.validations.map((v) => `- ${v}`).join(`
`)}
` : ""}
Your lens (your main hunting ground beyond the rules): ${CODE_LENSES[which]}.

Your assigned guideline rules — you are the ONLY reviewer checking these, so check every one explicitly: ${rules[which].join(", ")} (verbatim text in the rules snapshot from step 1).

Known findings from earlier rounds — do NOT re-report these unless the code has regressed:
${seenDigest || "(none — first round)"}

Report only real, evidenced issues. Severity: "blocking" = bug or guideline violation that must be fixed; "concern" = likely problem needing a fix or justification; "suggestion" = optional polish (never drives rework). For each finding give a stable key "<rule-id-or-gap>:<file-or-location>". Set confidence honestly — findings under ${cfg.confidenceMin} will be dropped.

You MUST return a rule_checklist entry with a pass/violation/na verdict and one line of evidence for every assigned rule (${rules[which].join(", ")}), the ac_checklist covering every AC (and addendum task) from step 2, plus your findings.`;
  }
  const reviews = await parallel([
    () => agent(reviewerPrompt("a"), { label: `review:${item.id}:a:r${roundLabel}`, phase: "Review", schema: FINDINGS_SCHEMA }),
    () => agent(reviewerPrompt("b"), { label: `review:${item.id}:b:r${roundLabel}`, phase: "Review", schema: FINDINGS_SCHEMA })
  ]);
  const tagged = reviews.map((r, i) => ({ r, which: i === 0 ? "a" : "b" })).filter((x) => Boolean(x.r));
  const allFindings = tagged.flatMap((x) => x.r.findings.map((f) => ({ ...f, id: `r${roundLabel}-${x.which}-${f.id}`, reviewer: x.which })));
  const checklists = Object.fromEntries(tagged.map((x) => [x.which, x.r.rule_checklist]));
  const acChecklists = Object.fromEntries(tagged.map((x) => [x.which, x.r.ac_checklist]));
  const gating = allFindings.filter((f) => f.severity !== "suggestion");
  const suggestions = allFindings.filter((f) => f.severity === "suggestion");
  log(`${item.id} round ${roundLabel}: ${gating.length} gating finding(s), ${suggestions.length} suggestion(s)`);
  const roundFile = `${cfg.dir}/reviews/${item.id}-code-round-${roundLabel}.md`;
  const verification = await agent(gating.length === 0 ? `You are the record-writer for deliverable ${item.id}, code-review round ${roundLabel}, of strapped run "${cfg.slug}". This round is CLEAN: the reviewers returned zero gating findings, so there is nothing to adjudicate and nothing to dedup. Do NOT re-review the code and do NOT read the worktree — your only job is the round record. Round-record format: ${cfg.conventionsFile}.

Write the round record to ${roundFile} with frontmatter: round: ${roundLabel}, seed_used: ${seedUsed}, reviewer_a_rules: ${JSON.stringify(rules.a)}, reviewer_b_rules: ${JSON.stringify(rules.b)}, new_confirmed: 0, outcome: converged, findings list = the suggestions below with status suggestion. Body: the suggestions plus the two rule checklists AND the two AC/addendum checklists verbatim.

Suggestions (non-gating, record only):
${JSON.stringify(suggestions, null, 2)}

Rule checklists: ${JSON.stringify(checklists, null, 2)}

AC/addendum checklists: ${JSON.stringify(acChecklists, null, 2)}

Return empty verdicts, empty new-confirmed ids, and empty duplicate ids.` : `You are the verify-consolidate agent for deliverable ${item.id}, code-review round ${roundLabel}, of strapped run "${cfg.slug}": a skeptical verifier adjudicating EVERY gating finding in one batch pass, then the round's consolidator writing its record. Round-record format: ${cfg.conventionsFile}.${confirmation ? `
This is a CONFIRMATION pass after the final budgeted round: its findings were all fixed, and this pass re-checks whether any NEW issue remains.` : ""}

Code reviewers claim the following issues in deliverable ${item.id} (worktree: ${item.worktree}, diff: git diff ${item.base}...${item.branch}).

The guideline rules behind rule-keyed findings and the checklists carry only their ids here — the verbatim rule text lives in the rules snapshot at ${rulesFile}; Read it whenever a rule's wording matters to a verdict.

Gating findings to adjudicate:
${JSON.stringify(gating, null, 2)}

Verification stance, applied to each finding independently: it is NOT a real issue unless the code proves otherwise. Read the actual code in the worktree and try to refute each claim — look for handling the reviewer missed, misread control flow, or a claim about code that does not exist. Cast one verdict per finding id — "confirmed" (the issue is proven real), "plausible" (credible but unproven), or "refuted" (not a real issue) — with a corrected confidence (0-100) that the issue is real and one line of evidence. A finding with verdict refuted, or confidence below ${cfg.confidenceMin}, does not survive.

Suggestions (non-gating, never verified, record only):
${JSON.stringify(suggestions, null, 2)}

Rule checklists: ${JSON.stringify(checklists, null, 2)}

AC/addendum checklists (per-item AC pass/violation/na verdicts from each reviewer, enumerating the deliverable plan's \`## Acceptance criteria\` plus any \`## Feedback addendum\` tasks): ${JSON.stringify(acChecklists, null, 2)}

Seen digest from prior rounds:
${seenDigest || "(none — first round)"}

Prior round record files, if any, live in ${cfg.dir}/reviews/ named ${item.id}-code-round-*.md — read them.

Consolidation tasks, over the findings that survive your verdicts:
1. Merge same-root-cause findings by key against BOTH this round's set and all prior rounds. A finding matching a prior round's key is a duplicate unless the prior record marks it fixed and it has regressed.
2. Write the round record to ${roundFile} with frontmatter: round: ${roundLabel}, seed_used: ${seedUsed}, reviewer_a_rules: ${JSON.stringify(rules.a)}, reviewer_b_rules: ${JSON.stringify(rules.b)}, new_confirmed: <count>, outcome: converged if zero new confirmed else revise, and the findings list with one entry per finding carrying { id, key, severity, verdict: confirmed|plausible|refuted, confidence, status } per the conventions (status: open for new confirmed, duplicate for duplicates). Body: full finding bodies (what/why/evidence/recommendation) plus the two rule checklists AND the two AC/addendum checklists (the per-item AC/addendum pass/violation/na verdicts).
3. Return your per-finding verdicts, the ids of truly-NEW confirmed findings (surviving and not duplicates), and the duplicate ids.`, { label: `verify:${item.id}:r${roundLabel}`, phase: "Verify", effort: "low", schema: VERIFY_SCHEMA });
  if (!verification) {
    if (gating.length)
      log(`${item.id} round ${roundLabel}: verifier cast no vote — ${gating.length} gating finding(s) excluded`);
    return { newConfirmed: [], suggestions, roundFile, converged: true };
  }
  const verdictById = new Map(verification.verdicts.map((v) => [v.id, v]));
  const surviving = gating.filter((f) => {
    const v = verdictById.get(f.id);
    return v !== undefined && v.verdict !== "refuted" && v.confidence >= cfg.confidenceMin;
  });
  const dropped = gating.length - surviving.length;
  if (dropped > 0)
    log(`${item.id} round ${roundLabel}: verify pass dropped ${dropped} finding(s)`);
  const newIds = new Set(verification.new_confirmed_ids);
  const newConfirmed = surviving.filter((f) => newIds.has(f.id));
  log(`${item.id} round ${roundLabel}: ${newConfirmed.length} NEW confirmed finding(s)`);
  return { newConfirmed, suggestions, roundFile, converged: newConfirmed.length === 0 };
}

// src/workflows/strapped-run/stages/implement.ts
function implementPrompt(cfg, item) {
  return `You are the implementation agent for deliverable ${item.id} of strapped run "${cfg.slug}". You have fresh context — everything you need is in the files below.

Work EXCLUSIVELY inside the worktree: ${item.worktree} (branch ${item.branch}, based on ${item.base}). This deliverable targets repo "${item.repo}" — never touch ${item.repoRoot} directly.

1. Read your deliverable plan in full: ${item.planFile}
2. Read the shared research digest: ${cfg.dir}/research.md
3. Read the project guidelines: every CLAUDE.md that applies (repo root at minimum).
${item.resumeNote ? `
This deliverable is being RESUMED. Prior state:
${item.resumeNote}
` : ""}
If the plan declares a \`## Preconditions\` section, verify each stated precondition FIRST. If any is not currently satisfied, do NOT implement and do NOT improvise around it (no vendoring, stubbing, or re-creating work the precondition says must land externally first): return status "blocked" with the blocker naming the unmet precondition — the node parks with that reason and is re-kicked later once the precondition holds.

Implement exactly what the plan specifies — its acceptance criteria are the contract. Write the tests the plan names (integration-style, public interfaces). Stay in scope: anything under "Out of scope" is off limits; note side-discoveries in your summary instead of fixing them.

Before finishing, ALL validations must pass inside the worktree:
${item.validations.map((v) => `- ${v}`).join(`
`)}

Commit your work on ${item.branch} with a Conventional-Commits message (\`<type>(${cfg.slug}): <description>\` — scope is the run slug, no \`${item.id}:\` title prefix; reference ${item.id} in the body). If validations pass, commit and return status "implemented" with validations_green true. If you hit a blocker you cannot resolve (missing dependency, contradictory plan, validation failure you cannot fix), commit what is safe, return status "blocked" with the blocker described — do NOT loop indefinitely.`;
}
function fixPrompt(cfg, item, findings, round) {
  return `You are the fix agent for deliverable ${item.id} of strapped run "${cfg.slug}", code-review round ${round}. Fresh context — everything you need is below.

Work EXCLUSIVELY inside the worktree: ${item.worktree} (branch ${item.branch}, based on ${item.base}). This deliverable targets repo "${item.repo}" — never touch ${item.repoRoot} directly.

1. Read the deliverable plan: ${item.planFile}
2. Read the research digest: ${cfg.dir}/research.md
3. Read the full round record: ${cfg.dir}/reviews/${item.id}-code-round-${round}.md

Confirmed findings you must fix:
${JSON.stringify(findings.map((f) => ({ id: f.id, key: f.key, severity: f.severity, location: f.location, what: f.what, recommendation: f.recommendation })), null, 2)}

Fix every finding. Then re-run ALL validations inside the worktree until green:
${item.validations.map((v) => `- ${v}`).join(`
`)}

Commit the fixes on ${item.branch}. Update the round record: flip each fixed finding's status from open to fixed. Return status "implemented" with validations_green true, or "blocked" with the blocker if a finding cannot be fixed as recommended (do not silently skip it).`;
}
async function implementOne(cfg, item) {
  const result = await agent(implementPrompt(cfg, item), {
    label: `implement:${item.id}`,
    phase: "Implement",
    schema: IMPLEMENT_SCHEMA
  });
  if (!result)
    return { item, outcome: "parked", parkedReason: "implementer agent failed", roundsUsed: 0 };
  if (result.status === "blocked" || !result.validations_green) {
    return { item, outcome: "parked", parkedReason: result.blocker || "validations not green after implementation", roundsUsed: 0, summary: result.summary };
  }
  return { item, outcome: "implemented", summary: result.summary, roundsUsed: 0 };
}
async function reviewFixLoop(cfg, state) {
  if (state.outcome === "parked")
    return { ...state, suggestions: [] };
  const item = state.item;
  if (cfg.codeRounds === 0) {
    log(`${item.id}: code-review budget 0 — skipping adversarial review`);
    return { item, outcome: "done", roundsUsed: 0, summary: state.summary, suggestions: [] };
  }
  const seen = [];
  const suggestions = [];
  let converged = false;
  let roundsUsed = 0;
  let parkedReason = null;
  let lastRoundFixedAll = false;
  for (let round = 1;round <= cfg.codeRounds; round++) {
    roundsUsed = round;
    lastRoundFixedAll = false;
    const review = await runCodeReviewRound(cfg, { item, round, confirmation: false, seen });
    suggestions.push(...review.suggestions);
    if (review.converged) {
      converged = true;
      break;
    }
    for (const f of review.newConfirmed)
      seen.push({ ...f, round, status: "open" });
    const fix = await agent(fixPrompt(cfg, item, review.newConfirmed, round), {
      label: `fix:${item.id}:r${round}`,
      phase: "Fix",
      schema: IMPLEMENT_SCHEMA
    });
    if (!fix || fix.status === "blocked" || !fix.validations_green) {
      parkedReason = fix && fix.blocker || `fix agent failed on round ${round}`;
      break;
    }
    for (const f of seen)
      if (f.status === "open")
        f.status = "fixed";
    lastRoundFixedAll = true;
  }
  if (!converged && !parkedReason && lastRoundFixedAll) {
    const confirm = await runCodeReviewRound(cfg, { item, round: cfg.codeRounds, confirmation: true, seen });
    suggestions.push(...confirm.suggestions);
    if (confirm.converged) {
      converged = true;
    } else {
      for (const f of confirm.newConfirmed)
        seen.push({ ...f, round: cfg.codeRounds, status: "open" });
      parkedReason = `confirmation pass after round ${cfg.codeRounds} surfaced open findings: ${confirm.newConfirmed.map((f) => f.key).join(", ")}`;
    }
  }
  if (converged) {
    return { item, outcome: "done", roundsUsed, summary: state.summary, suggestions };
  }
  const open = seen.filter((f) => f.status === "open").map((f) => f.key);
  return {
    item,
    outcome: "parked",
    roundsUsed,
    parkedReason: parkedReason || `code-review budget (${cfg.codeRounds}) exhausted with open findings: ${open.join(", ")}`,
    summary: state.summary,
    suggestions
  };
}
function coordinatorPrompt(cfg, pass, only) {
  const stateScript = cfg.scripts.state;
  const worktreeScript = cfg.scripts.worktree;
  const header = `You are the wave coordinator (pass ${pass}) of the implement stage of strapped run "${cfg.slug}". You are a mechanical executor: run exactly the commands below via Bash and return the JSON described — the scripts do all the computing, you are a pipe. Contract for every script: the "Harness scripts" section of ${cfg.conventionsFile}.

Run root: ${cfg.dir}
State script: node ${stateScript} <command> ...
Worktree script: ${worktreeScript}
${pass === 1 ? `
First pass only — flip the manifest first: run \`node ${stateScript} manifest-status ${cfg.dir} implementing\` (a same-status flip is an idempotent no-op on resume).
` : ""}`;
  return `${header}
1. Run \`node ${stateScript} dag ${cfg.dir}${only ? ` --only ${only}` : ""}\` EXACTLY ONCE, FIRST — its \`ready\`, \`topo\`, \`blocked\`, and \`remaining\` fields are authoritative; consume them verbatim, never recompute readiness or remaining yourself, and NEVER re-run dag after a transition (your paste below is THIS first output). This pass's wave = every node in \`ready\` PLUS every node whose status in the dag's \`nodes\` list is \`in-progress\` with a recorded worktree (an interrupted implementation to resume — compose its resumeNote from its frontmatter).
2. Run \`node ${stateScript} resolve ${cfg.slug}\` for the repos map (per repo: root, validations, worktreeRoot, provisioning).
3. For EACH node in \`ready\` (this pass's wave):
   - Look up its repo's { root, validations, worktreeRoot, provisioning } via the node's \`repo\` field.
   - Worktree path: <worktreeRoot>/${cfg.slug}/<id>; branch and base come from the node's frontmatter.
   - Run \`${worktreeScript} <repoRoot> <worktreePath> <branch> <base>\` (idempotent: reuses a matching worktree, re-attaches an existing branch, otherwise creates from base; a non-zero exit is a hard stop — report it, don't improvise). Apply the repo's \`provisioning\` instructions only to a FRESH worktree (\`created: true\`), placeholder values only, never real secrets.
   - Record: \`node ${stateScript} set <deliverableFile> worktree <worktreePath>\` then \`node ${stateScript} transition <deliverableFile> in-progress\` (a \`parked\` node readmitted via --only flips parked → in-progress; in-progress → in-progress is an idempotent no-op).
   - resumeNote: null for a fresh (\`pending\`) node. For a re-dispatched node (was \`in-progress\` or \`parked\`), compose a short string from its frontmatter (\`parked_reason\`, \`review_rounds_used\`) and the latest ${cfg.dir}/reviews/<id>-code-round-*.md record — open findings and what was already done.
Return \`items\` (one per ready node: id, repo, repoRoot, validations, planFile as the ABSOLUTE deliverable file path, worktree, branch, base, resumeNote, pr — the node's \`pr:\` frontmatter URL, null when none), \`dag\` = an object with EXACTLY four keys — \`ready\`, \`remaining\`, \`blocked\` copied unchanged from your FIRST dag run's printed JSON, plus \`resumable\` = the ids from that same output's \`nodes\` list whose status is \`in-progress\` ([] when none); include NO other dag fields (nodes, topo, manifest are rejected by the schema). The workflow validates your wave against this paste — a wave that omits a ready node is rejected. When the dag's \`remaining\` is 0, return items: [].`;
}
function applyPrompt(cfg, pass, results) {
  const stateScript = cfg.scripts.state;
  const outcomes = results.map((r) => ({
    id: r.item.id,
    deliverableFile: r.item.planFile,
    outcome: r.outcome,
    roundsUsed: r.roundsUsed,
    parkedReason: r.parkedReason || null,
    pr: r.item.pr || null
  }));
  return `You are the outcome applier (pass ${pass}) of the implement stage of strapped run "${cfg.slug}". You are a mechanical executor: apply each outcome below to its deliverable's frontmatter by running exactly the state-script commands described (contract: the "Harness scripts" section of ${cfg.conventionsFile}) and return the JSON described. Never hand-edit frontmatter.

State script: node ${stateScript} <command> ...

Wave outcomes:
${JSON.stringify(outcomes, null, 2)}

Per outcome:
- outcome "done": \`node ${stateScript} transition <deliverableFile> done\`.
- outcome "parked": \`node ${stateScript} transition <deliverableFile> parked\` then \`node ${stateScript} set <deliverableFile> parked_reason "<parkedReason>"\`.
- always: \`node ${stateScript} set <deliverableFile> review_rounds_used <roundsUsed>\`.

Return applied: one entry per outcome { id, status } with the final on-disk status. Do not run anything else.`;
}
async function implementStage(cfg) {
  const a = stageArgsFor(cfg, "implement");
  const only = a.only || null;
  const outcomes = [];
  let blocked = [];
  let allDone = false;
  let pass = 0;
  let maxPasses = Infinity;
  while (pass < maxPasses) {
    pass++;
    let wave = await agent(coordinatorPrompt(cfg, pass, only), {
      label: `coordinate:${pass}`,
      phase: "Implement",
      schema: WAVE_SCHEMA
    });
    if (!wave)
      throw new Error(`implement stage: coordinator agent failed on pass ${pass}`);
    const matchesDag = (w) => {
      const itemIds = new Set(w.items.map((i) => i.id));
      const dispatchable = new Set([...w.dag.ready, ...w.dag.resumable]);
      return w.dag.ready.every((id) => itemIds.has(id)) && [...itemIds].every((id) => dispatchable.has(id));
    };
    if (!matchesDag(wave)) {
      log(`pass ${pass}: coordinator wave [${wave.items.map((i) => i.id).join(", ")}] does not match dag ready [${wave.dag.ready.join(", ")}] — re-dispatching once`);
      const mismatchNote = `

RETRY — your previous wave was REJECTED: its items [${wave.items.map((i) => i.id).join(", ")}] did not match its own dag paste's ready [${wave.dag.ready.join(", ")}]. Return EXACTLY one items entry per node in the dag command's ready list — no omissions, no extras.`;
      wave = await agent(coordinatorPrompt(cfg, pass, only) + mismatchNote, {
        label: `coordinate:${pass}:retry`,
        phase: "Implement",
        schema: WAVE_SCHEMA
      });
      if (!wave)
        throw new Error(`implement stage: coordinator agent failed on pass ${pass} retry`);
      if (!matchesDag(wave)) {
        throw new Error(`implement stage: coordinator wave [${wave.items.map((i) => i.id).join(", ")}] does not match its own dag ready [${wave.dag.ready.join(", ")}] after a retry on pass ${pass}`);
      }
    }
    const remaining = wave.dag.remaining;
    if (pass === 1)
      maxPasses = remaining + 1;
    blocked = wave.dag.blocked;
    if (remaining === 0) {
      allDone = true;
      break;
    }
    if (!wave.items.length) {
      log(`pass ${pass}: no dispatchable node with ${remaining} remaining — stopping`);
      break;
    }
    log(`pass ${pass} wave: ${wave.items.map((i) => i.id).join(", ")}`);
    const results = await pipeline(wave.items, (item) => implementOne(cfg, item), (state) => reviewFixLoop(cfg, state));
    const waveResults = results.filter(Boolean);
    const applied = await agent(applyPrompt(cfg, pass, waveResults), {
      label: `apply:${pass}`,
      phase: "Implement",
      effort: "low",
      schema: APPLY_SCHEMA
    });
    if (!applied)
      throw new Error(`implement stage: outcome-applier agent failed on pass ${pass}`);
    outcomes.push(...waveResults.map((r) => ({
      id: r.item.id,
      outcome: r.outcome,
      roundsUsed: r.roundsUsed,
      parkedReason: r.parkedReason || null,
      summary: r.summary || null,
      suggestions: (r.suggestions || []).map((s) => ({ key: s.key, what: s.what, location: s.location }))
    })));
    if (!waveResults.some((r) => r.outcome === "done")) {
      log(`pass ${pass}: zero newly-done progress — stopping`);
      break;
    }
    const doneResults = waveResults.filter((r) => r.outcome === "done");
    const remainingAfter = wave.dag.remaining - doneResults.length;
    if (remainingAfter <= 0) {
      const appliedStatus = new Map(applied.applied.map((n) => [n.id, n.status]));
      const unapplied = doneResults.filter((r) => appliedStatus.get(r.item.id) !== "done");
      if (unapplied.length) {
        log(`pass ${pass}: wrap-up shortcut skipped — on-disk status disagrees with done outcome for [${unapplied.map((r) => r.item.id).join(", ")}] — dispatching the next coordinator pass`);
      } else {
        const doneIds = new Set(doneResults.map((r) => r.item.id));
        blocked = wave.dag.blocked.filter((b) => !doneIds.has(b.id));
        allDone = true;
        log(`pass ${pass}: all ${doneResults.length} remaining node(s) done — skipping wrap-up coordinator`);
        break;
      }
    }
  }
  return { outcomes, allDone, blocked };
}

// src/workflows/strapped-run/stages/plan.ts
var MAX_RESEARCH_PER_ROUND = 6;
function slugifyTopic(topic) {
  return topic.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
function uniqueRequests(requests, seen) {
  const out = [];
  const local = new Set;
  for (const req of requests) {
    const slug = slugifyTopic(req.topic ?? "");
    if (slug === "" || seen.has(slug) || local.has(slug))
      continue;
    local.add(slug);
    out.push({ slug, topic: req.topic, brief: req.brief ?? "" });
  }
  return out;
}
function plannerInputs(cfg, a) {
  return `Source plan (the original ask): ${a.sourcePlan}
Target repos (the run state is keyed by the run slug, not by any repo; the work spans these repos — an unordered set):
${repoList(a.repos)}
Output directory (already scaffolded): ${cfg.dir}
Conventions you MUST follow for every file format: ${cfg.conventionsFile}`;
}
function researchSteps(cfg) {
  return `1. Read the source plan in full, then research each target repo's codebase thoroughly: architecture, the modules the ask touches, existing utilities to reuse, test patterns.
2. Write ${cfg.dir}/research.md — a distilled digest (~300 lines max): architecture notes, key files with one-line roles, library/API findings, decisions with rationale, known pitfalls. This is the only research context implementers will ever see.`;
}
function planWritingSteps(cfg) {
  const stateScript = cfg.scripts.state;
  return `3. Split the work into deliverables by discrete theme, forming a DAG: independent work has no deps, dependent work lists its parent deliverable ids. Keep one coherent theme in a single deliverable so a reviewer can grasp the whole change in one PR — split a theme into multiple deliverables only when its estimated meaningful diff (excluding generated code, dependency/lockfile bumps, generated clients/schemas, vendored code, and large fixtures) exceeds ~1,000 changed lines. Prefer a few cohesive, independently-shippable nodes over many fragments that scatter one theme across PRs. Assign each deliverable to exactly one target repo.
4. Write one self-contained file per deliverable at ${cfg.dir}/deliverables/<id>-<kebab>.md per the conventions (ids are EXACTLY D1, D2, D3, ... — capital D then the ordinal, in filenames, frontmatter, branches, and deps alike) (frontmatter: id, title, deps, repo: <one of the target repo names above>, status: pending, branch: strapped/${cfg.slug}/<id>-<kebab>, base, worktree: null, pr: null, review_rounds_used: 0, feedback_rounds_used: 0, parked_reason: null, estimated_diff_lines; body sections under these EXACT verbatim headers — \`## Context\`, \`## Files to touch\`, \`## Implementation steps\`, \`## Acceptance criteria\`, \`## Tests\`, \`## Out of scope\` — the review machinery keys on the \`## Acceptance criteria\` header literally, so no case or wording variation; a deliverable covered by step 5 additionally carries a \`## Preconditions\` section). Set base per the cross-repo base rule: a deliverable's base is a parent branch WITHIN THE SAME repo, otherwise that repo's main (roots, and any cross-repo child, base on their own repo's main — you can never branch across repos). A fresh implementer seeded with ONLY this file plus research.md must be able to do the work.
5. A deliverable MAY depend on a parent whose work must first become available to it through some external landing step outside this run's control (a cross-repo child bases on its own repo's main and never has a sibling repo's unmerged branch). Plan such work IN the DAG anyway — never push it out of the plan as an out-of-band follow-up. Record the prerequisite in the child's body under a \`## Preconditions\` section (a short note stating what must be TRUE before implementation can start — checkable, not aspirational); at implement time an unmet precondition parks the node for a later re-kick instead of blocking the plan.
6. Write ${cfg.dir}/manifest.md per the conventions (status: in-review, seed: ${cfg.seed}, budgets — record the EFFECTIVE budgets of this run: plan_rounds: ${cfg.planRounds}, code_rounds: ${cfg.codeRounds}, research_rounds: ${cfg.researchRounds}, confidence_min: ${cfg.confidenceMin} — the repos: map listing every target repo above per the conventions — name, root, config path (repos: is an unordered set, no repo is special); the deliverables list with ids/files/repos/deps, theme summary, ASCII DAG sketch).
7. After all plan artifacts are written, run \`node ${stateScript} commit ${cfg.dir}\` via Bash so the run's state root is git-backed from birth (it git-inits the state root if absent and commits the artifacts). Best-effort: proceed even if it reports an error.`;
}
function classicPlannerPrompt(cfg, a) {
  return `You are the planning agent for strapped run "${cfg.slug}". Produce a complete, reviewable implementation plan from a large source plan document.

${plannerInputs(cfg, a)}

Procedure:
${researchSteps(cfg)}
${planWritingSteps(cfg)}

Return the deliverable list and a one-paragraph summary.`;
}
function leadPlannerPrompt(cfg, a) {
  return `You are the planning agent for strapped run "${cfg.slug}". Produce a complete, reviewable implementation plan from a large source plan document.

${plannerInputs(cfg, a)}

Research delegation: this run budgets ${cfg.researchRounds} BFS research rounds, counting your own research as round 1. You may enqueue research topics via research_requests; each becomes a delegated researcher agent running in its own isolated context, writing a fragment file under ${cfg.dir}/research/. Treat enqueueing a research task exactly as you would treat spawning a research subagent if you had that capability — the same judgment and the same restraint: delegation is for discrete topics that genuinely benefit from an isolated context window, and liberal delegation wastes tokens and wall clock. Most asks need no delegation at all.

Procedure (steps 2–7 apply only when you return an EMPTY research_requests list):
${researchSteps(cfg)}
${planWritingSteps(cfg)}

Delegation exit — when you return a NON-EMPTY research_requests list, replace steps 2–7 with: write ONLY your own round-1 findings as fragment files under ${cfg.dir}/research/<topic-slug>.md (lowercase kebab slug of each fragment's topic), write NO research.md, NO manifest.md, and NO deliverables/ files (a plan-writer agent consolidates every fragment and writes those after the delegated research rounds finish), and return empty deliverables plus research_requests (one { topic, brief } per delegated topic — the brief tells that researcher what to find out and why).

Return the deliverable list and a one-paragraph summary (deliverables is empty on the delegation exit).`;
}
function researcherPrompt(cfg, a, t, otherTopics, round, isFinal) {
  const fragment = `${cfg.dir}/research/${t.slug}.md`;
  const ownership = otherTopics.length === 0 ? "" : `
These topics are already owned by other researchers: ${otherTopics.join(", ")}; stay focused on your own topic — you may read their fragments under ${cfg.dir}/research/ for context, but don't duplicate their work in yours.
`;
  const enqueueStep = isFinal ? "" : `
3. You MAY request further research for the next round by returning research_requests (one { topic, brief } per topic). Treat enqueueing a research task exactly as you would treat spawning a research subagent if you had that capability — the same judgment and the same restraint: most topics need no further delegation, so return an empty list unless a discrete sub-topic genuinely needs its own isolated context.`;
  const returnLine = isFinal ? `Return { topic, notes_file, summary } — topic "${t.slug}", notes_file "${fragment}", and a one-paragraph summary of your findings.` : `Return { topic, notes_file, summary, research_requests } — topic "${t.slug}", notes_file "${fragment}", a one-paragraph summary of your findings, and research_requests (empty unless step 3 applies).`;
  return `You are a delegated research agent for strapped run "${cfg.slug}" (plan-stage research round ${round} of ${cfg.researchRounds}). Research exactly ONE topic in this isolated context and write your findings as a fragment file.

Your topic: ${t.topic}
Brief from the lead: ${t.brief}

Source plan (the original ask): ${a.sourcePlan}
Target repos (an unordered set — the work spans these repos):
${repoList(a.repos)}
Run directory: ${cfg.dir}
${ownership}
Procedure:
1. Research your topic thoroughly across the target repos and the source plan: architecture, the modules the topic touches, key files, existing utilities to reuse, library/API findings, pitfalls.
2. Write ${fragment} — a distilled, self-contained fragment (~100 lines max): key files with one-line roles, findings, decisions with rationale, known pitfalls. It will be consolidated into the run's research digest, so keep it scoped to your topic.${enqueueStep}

${returnLine}`;
}
function planWriterPrompt(cfg, a) {
  return `You are the plan-writer for strapped run "${cfg.slug}". The planning lead and its delegated researchers have finished their research; consolidate it and produce the complete, reviewable implementation plan.

${plannerInputs(cfg, a)}

Procedure:
1. Read the source plan in full, then read EVERY research fragment under ${cfg.dir}/research/ — the lead's own findings plus each delegated researcher's fragment.
2. Write ${cfg.dir}/research.md — consolidate the fragments into one distilled digest (~300 lines max): architecture notes, key files with one-line roles, library/API findings, decisions with rationale, known pitfalls. This is the only research context implementers will ever see. Then perform steps 3–7:
${planWritingSteps(cfg)}

Return the deliverable list and a one-paragraph summary.`;
}
async function runResearchRounds(cfg, a, initial) {
  const seen = new Set;
  let pending = uniqueRequests(initial, seen);
  for (let round = 2;round <= cfg.researchRounds && pending.length > 0; round++) {
    const batch = pending.slice(0, MAX_RESEARCH_PER_ROUND);
    const dropped = pending.slice(MAX_RESEARCH_PER_ROUND);
    if (dropped.length > 0) {
      log(`plan research round ${round}: clamped to ${MAX_RESEARCH_PER_ROUND} researchers — dropped ${dropped.map((t) => t.slug).join(", ")}`);
    }
    for (const t of batch)
      seen.add(t.slug);
    const isFinal = round === cfg.researchRounds;
    const results = await parallel(batch.map((t) => () => {
      const others = [...seen].filter((s) => s !== t.slug);
      return agent(researcherPrompt(cfg, a, t, others, round, isFinal), {
        label: `researcher:${t.slug}`,
        schema: isFinal ? RESEARCH_FINAL_SCHEMA : RESEARCH_SCHEMA
      });
    }));
    const nextRequests = [];
    for (let i = 0;i < batch.length; i++) {
      const t = batch[i];
      if (t === undefined)
        continue;
      const result = results[i];
      if (result === null || result === undefined) {
        log(`plan research round ${round}: researcher ${t.slug} returned no result — skipped`);
        continue;
      }
      if (!isFinal)
        nextRequests.push(...result.research_requests ?? []);
    }
    pending = isFinal ? [] : uniqueRequests(nextRequests, seen);
  }
}
async function planStage(cfg, ctx) {
  const a = stageArgsFor(cfg, "plan");
  const stateScript = cfg.scripts.state;
  const delegating = cfg.researchRounds > 1;
  const plan = await agent(delegating ? leadPlannerPrompt(cfg, a) : classicPlannerPrompt(cfg, a), { label: "planner", schema: delegating ? PLAN_LEAD_SCHEMA : PLAN_SCHEMA });
  if (!plan)
    throw new Error("plan stage: planner agent failed");
  const requests = delegating ? plan.research_requests ?? [] : [];
  let deliverables = plan.deliverables;
  let summary = plan.summary;
  if (requests.length > 0) {
    log(`plan delegating research: ${requests.length} request(s)`);
    await runResearchRounds(cfg, a, requests);
    const written = await agent(planWriterPrompt(cfg, a), { label: "plan-writer", schema: PLAN_SCHEMA });
    if (!written)
      throw new Error("plan stage: plan-writer agent failed");
    deliverables = written.deliverables;
    summary = written.summary;
  }
  log(`plan produced: ${deliverables.length} deliverable(s)`);
  const review = await runReviewLoop(cfg, {
    ask: a.sourcePlan,
    repos: a.repos,
    artifactDescription: "a produced implementation plan",
    artifactLocation: "manifest.md, research.md, and every file in deliverables/",
    artifactNoun: "plan",
    verifyArtifactPhrase: "the implementation plan",
    roundFilePrefix: "plan-round",
    maxRounds: cfg.planRounds,
    reviserPromptFn: (newConfirmed, roundFile) => `You are the plan reviser for strapped run "${cfg.slug}". Close every confirmed review finding by editing the plan files in ${cfg.dir} (manifest.md, research.md, deliverables/*.md), keeping every file conformant to ${cfg.conventionsFile}. Original ask for reference: ${a.sourcePlan}. Target repos (fix repo assignments and cross-repo base rules against these):
${repoList(a.repos)}

Confirmed findings to close (full bodies also in ${roundFile}):
${JSON.stringify(newConfirmed.map((f) => ({ id: f.id, key: f.key, location: f.location, what: f.what, recommendation: f.recommendation })), null, 2)}

For each finding: apply the fix (this may mean splitting a deliverable that mixes unrelated themes or exceeds the ~1,000-line meaningful-diff threshold, adding a missing deliverable, fixing deps in BOTH the manifest and the deliverable frontmatter, adding acceptance criteria or tests, or correcting a wrong assumption after re-checking the code). Then update ${roundFile}: flip each addressed finding's status from open to fixed. Return one line per finding: id — what you changed.`
  });
  if (review.converged && ctx.hasLaterStage) {
    const approve = await agent(`You are a mechanical executor for strapped run "${cfg.slug}". Run exactly this command via Bash and return its JSON output (contract: the "Harness scripts" section of ${cfg.conventionsFile}):

node ${stateScript} manifest-status ${cfg.dir} approved

Return { "changed": <the command's changed field> }. Do not run anything else.`, { label: "approve", effort: "low", schema: APPROVE_SCHEMA });
    if (!approve)
      throw new Error("plan stage: approve executor agent failed");
    log("plan converged — manifest approved for the chained stages");
  }
  return {
    converged: review.converged,
    rounds: review.rounds,
    deliverables,
    outstanding: review.outstanding,
    summary
  };
}

// src/workflows/strapped-run/stages/pr.ts
async function prStage(cfg, ctx) {
  const a = stageArgsFor(cfg, "pr");
  const dryRun = Boolean(a.dryRun);
  const stateScript = cfg.scripts.state;
  if (!ctx.ranImplement) {
    const probe = await agent(`You are a mechanical executor for strapped run "${cfg.slug}". Run exactly this command via Bash and return the JSON described (contract: the "Harness scripts" section of ${cfg.conventionsFile}):

node ${stateScript} dag ${cfg.dir}

Return { "remaining": <the dag's remaining field verbatim — never recompute it>, "notDone": [<the ids of the nodes whose status is NOT done/pr-open/merged>] }. Do not run anything else.`, { label: "pr-gate", phase: "PR", effort: "low", schema: PROBE_SCHEMA });
    if (!probe)
      throw new Error("pr stage: dag probe agent failed");
    if (probe.remaining > 0) {
      log(`pr stage gate failed: ${probe.remaining} node(s) not yet done`);
      return {
        gateFailed: true,
        notDone: probe.notDone,
        prs: [],
        dryRun,
        summary: `pr stage did not run: ${probe.remaining} node(s) not yet done — ${probe.notDone.join(", ")}`
      };
    }
  }
  const result = await agent(`You are the PR stage of strapped run "${cfg.slug}". Create the stacked GitHub PRs for this run's done deliverables — mechanically, per the documented procedure. All state reads/writes go through the state script: \`node ${stateScript} <command> ...\` (contract in the "Harness scripts" section of ${cfg.conventionsFile}).

Procedure — the "Stacked PRs" section of ${cfg.conventionsFile} is authoritative; read it first:
1. Run \`node ${stateScript} resolve ${cfg.slug}\` for the repos map (each repo's absolute root) and \`node ${stateScript} dag ${cfg.dir}\` for the nodes and the authoritative \`topo\` order — never hand-roll either.
2. Candidates: \`status: done\` nodes whose parents are all done, pr-open, or merged, processed in \`topo\` order.
3. Per candidate, in that deliverable's OWN repo (every git/gh operation pinned to it via \`git -C <repoRoot>\` / running gh inside <repoRoot>):
   - \`git -C <repoRoot> push -u origin <branch>\`
   - \`gh pr create --head <branch> --base <parent-branch-if-same-repo-else-main> --title "<conventional title>" --body-file <generated>\` — base per the cross-repo base rule (the parent deliverable's branch only when the parent is in the same repo; a root or cross-repo child bases on that repo's main). Title and body follow the conventions' "PR titles and bodies (Conventional Commits)" spec, which is the DEFAULT and defers: if the repo config, the repo's CLAUDE.md, or the user's Claude settings/guidelines already establish a PR-title or commit convention, follow THAT and do not overwrite it; only when no such convention is supplied, default to the conventional format — title \`<type>(${cfg.slug}): <description>\` — scope is the run slug "${cfg.slug}", \`<type>\` chosen from the deliverable's primary nature (feat/fix/refactor/perf/docs/test/build/ci/chore per the rubric there; \`!\` before the colon for a breaking change), \`<description>\` an imperative, lower-case summary of THIS deliverable with no trailing period (NOT a \`<Did>:\`-prefixed title) — keep the title SHORT: aim ~50 chars for the whole line, hard ceiling ~72. Body: a blank line then imperative what/why prose in natural unwrapped paragraphs (never insert manual line breaks inside a paragraph — GitHub wraps prose itself), then the retained structured pieces — one-paragraph summary, the acceptance criteria as a checklist, a Stack table of the whole DAG grouped by repo, and \`Depends on #<parent PR>\` for same-repo non-roots — then footers (\`BREAKING CHANGE:\` when applicable).
   - Record via the state script: \`node ${stateScript} set <deliverableFile> pr <url>\` then \`node ${stateScript} transition <deliverableFile> pr-open\`.
4. After all creations, refresh every stack table via \`gh pr edit <num> --body-file <regenerated>\` so earlier PRs link the later ones.

Guardrails (binding):
- Never push \`main\`, never merge PRs, never \`--force\` (only \`--force-with-lease\`) — enforced per repo (every git op runs \`-C <deliverableRepoRoot>\`).
- If \`gh\` is unauthenticated or a branch has no commits beyond its base, report and skip that node rather than failing the stage: return it with \`skipped: true\` and a human-readable \`reason\`, and continue with the remaining nodes.
${dryRun ? "\nDRY RUN — print-only: execute NOTHING that mutates (no push, no pr create/edit, no state-script set/transition). Print every would-be git/gh/state command, return them in `summary`, and return every candidate with `url: null` and `skipped: true`.\n" : ""}
Return \`prs\` — one entry per candidate node \`{ id, url, skipped, reason }\` (\`url\` null when skipped, \`reason\` null when created) — and a one-paragraph \`summary\` of what was created and what was skipped.`, { label: "pr-create", phase: "PR", schema: PR_SCHEMA });
  if (!result)
    throw new Error("pr stage: pr agent failed");
  log(`pr stage: ${result.prs.length} node(s) processed${dryRun ? " (dry run)" : ""}`);
  return { prs: result.prs, summary: result.summary, dryRun };
}

// src/workflows/strapped-run/main.ts
var STAGES = {
  plan: planStage,
  implement: implementStage,
  pr: prStage
};
function gateFailed(name, result) {
  if (name === "plan")
    return "converged" in result && !result.converged;
  if (name === "implement")
    return "allDone" in result && !result.allDone;
  if (name === "pr")
    return Boolean("gateFailed" in result && result.gateFailed);
  return false;
}
async function main() {
  const cfg = parseConfig(args);
  const results = {};
  const completed = [];
  let stoppedAt = null;
  for (const [i, name] of cfg.stages.entries()) {
    phase(name);
    const ctx = {
      hasLaterStage: i < cfg.stages.length - 1,
      ranImplement: completed.includes("implement")
    };
    const result = await STAGES[name](cfg, ctx);
    if (!result)
      throw new Error(`stage "${name}" returned no result`);
    results[name] = result;
    if (gateFailed(name, result)) {
      stoppedAt = name;
      log(`stage "${name}" gate failed — stopping the dispatch`);
      break;
    }
    completed.push(name);
  }
  return { slug: cfg.slug, stages: cfg.stages, completed, stoppedAt, results };
}

return await main()
