// Guards the committed-artifact rule: every deployable under
// plugins/strapped/scripts/ (and later workflows/) must be byte-identical to
// what `bun run build` produces from src/. An edit to src/ without a rebuild —
// or a hand-edit of a generated file — turns this test red.

import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { test } from 'bun:test'
import { fileURLToPath } from 'node:url'
import { BUILDS, buildCli, findStale } from '../tools/build.ts'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

test('bun tools/build.ts --check exits 0 on the committed tree', () => {
  // process.execPath is the bun binary under `bun test` — exactly what runs the build.
  const res = spawnSync(process.execPath, [join(ROOT, 'tools', 'build.ts'), '--check'], {
    encoding: 'utf8',
  })
  assert.equal(res.status, 0, `--check reported stale artifacts:\n${res.stderr}${res.stdout}`)
})

test('generated artifacts carry shebang, GENERATED header, and the exec bit', async () => {
  for (const spec of BUILDS) {
    const built = await buildCli(spec)
    const lines = built.split('\n')
    assert.equal(lines[0], '#!/usr/bin/env node', `${spec.outfile}: line 1 must be the node shebang`)
    assert.match(
      lines[1] ?? '',
      /^\/\/ GENERATED by tools\/build\.ts from .+ — do not edit; rebuild: bun run build$/,
      `${spec.outfile}: line 2 must be the GENERATED header`
    )
    const { mode } = statSync(join(ROOT, spec.outfile))
    assert.equal(mode & 0o111, 0o111, `${spec.outfile}: must be executable (chmod 755)`)
  }
})

test('findStale flags an artifact whose bytes differ from a fresh build', async () => {
  const spec = BUILDS[0]
  assert.ok(spec, 'build registry must not be empty')

  const dir = mkdtempSync(join(tmpdir(), 'strapped-build-sync-'))
  const mutated = join(dir, 'resolve-chain.mjs')
  writeFileSync(mutated, readFileSync(join(ROOT, spec.outfile), 'utf8') + '// hand edit\n')
  const missing = join(dir, 'never-built.mjs')

  const stale = await findStale([
    { entry: spec.entry, outfile: mutated },
    { entry: spec.entry, outfile: missing },
    spec, // the committed artifact itself stays clean
  ])
  assert.deepEqual(stale, [mutated, missing])
})
