// Permanent enforcement of the source plan's final acceptance criteria:
//
//  1. "No more javascript should exist once done (except for deployables)."
//     The only tracked *.js/*.mjs/*.cjs files are the four committed
//     deployables generated by tools/build.ts, each carrying the GENERATED
//     marker. Anyone who hand-writes JS, or commits a generated artifact
//     without its marker, turns this red.
//
//  2. "No `any` or other workarounds to make it compile." Every *.ts source
//     under src/, tools/, and tests/ is free of `any` and of the compile-
//     suppression escapes, so a green `tsc --noEmit` can never have been
//     bought with a suppression comment.

import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { readFileSync, readdirSync } from 'node:fs'
import { basename, join } from 'node:path'
import { test } from 'bun:test'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url))

const GENERATED_MARKER = 'GENERATED by tools/build.ts'

// The complete, exhaustive list of JavaScript the repo is allowed to track:
// the deployables downloaders run under node, generated from src/ by the build.
const DEPLOYABLES = [
  'plugins/strapped/scripts/resolve-chain.mjs',
  'plugins/strapped/scripts/state.mjs',
  'plugins/strapped/scripts/sync-chain-skills.mjs',
  'plugins/strapped/workflows/strapped-run.js',
].sort()

test('the only tracked JavaScript is the generated, marker-carrying deployables', () => {
  const ls = spawnSync('git', ['-C', REPO_ROOT, 'ls-files', '-z', '*.js', '*.mjs', '*.cjs'], {
    encoding: 'utf8',
  })
  assert.equal(ls.status, 0, ls.stderr)
  const tracked = ls.stdout.split('\0').filter(Boolean).sort()

  // Exactly the deployables — no more, no fewer.
  assert.deepEqual(tracked, DEPLOYABLES)

  // Each is a genuine build artifact (hand-authored JS at these paths, or a
  // stripped marker, would fail here even though the path list still matched).
  for (const rel of tracked) {
    const src = readFileSync(join(REPO_ROOT, rel), 'utf8')
    assert.ok(src.includes(GENERATED_MARKER), `${rel} lacks the "${GENERATED_MARKER}" marker`)
  }
})

// The escapes that would let `tsc --noEmit` pass without honest types. Written
// as whitespace-tolerant regexes so reformatting cannot smuggle one past.
const FORBIDDEN: { label: string; re: RegExp }[] = [
  { label: 'type annotation ": any"', re: /:\s*any\b/ },
  { label: 'assertion "as any"', re: /\bas\s+any\b/ },
  { label: 'type argument "<any>"', re: /<any>/ },
  { label: 'double assertion "as unknown as"', re: /\bas\s+unknown\s+as\b/ },
  { label: '"@ts-ignore"', re: /@ts-ignore/ },
  { label: '"@ts-expect-error"', re: /@ts-expect-error/ },
  { label: '"@ts-nocheck"', re: /@ts-nocheck/ },
]

// This guard is the one file that must contain the forbidden literals (to
// search for them), so it is exempt from its own scan.
const SELF = basename(fileURLToPath(import.meta.url))

function tsFilesUnder(root: string): string[] {
  const dir = join(REPO_ROOT, root)
  return readdirSync(dir, { recursive: true })
    .map(entry => String(entry))
    .filter(rel => rel.endsWith('.ts') && basename(rel) !== SELF)
    .map(rel => join(root, rel))
}

test('no `any` and no compile-suppression escapes anywhere in src/, tools/, or tests/', () => {
  const files = ['src', 'tools', 'tests'].flatMap(tsFilesUnder)
  assert.ok(files.length > 0, 'expected TypeScript sources to scan')

  const offenders: string[] = []
  for (const rel of files) {
    const lines = readFileSync(join(REPO_ROOT, rel), 'utf8').split('\n')
    lines.forEach((line, i) => {
      for (const { label, re } of FORBIDDEN) {
        if (re.test(line)) offenders.push(`${rel}:${i + 1}  ${label}  →  ${line.trim()}`)
      }
    })
  }

  assert.deepEqual(offenders, [], `forbidden type escapes found:\n${offenders.join('\n')}`)
})
