// Spawns the REAL plugins/strapped/scripts/sync-chain-skills.mjs with --home
// at a temp dir (state-env/hook-env pattern): wrappers are generated under
// <home>/.claude/skills/strapped-run-<chain>/, marked, idempotent, pruned when
// their chain no longer resolves, and never touch unmarked files.

import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { test } from 'bun:test'
import { fileURLToPath } from 'node:url'
import { NODE } from './helpers/node-bin.ts'

const SCRIPT = fileURLToPath(new URL('../plugins/strapped/scripts/sync-chain-skills.mjs', import.meta.url))

interface SyncJson {
  written: string[]
  unchanged: string[]
  pruned: string[]
}

function makeHome(anchor?: unknown): string {
  const home = mkdtempSync(join(tmpdir(), 'strapped-sync-'))
  mkdirSync(join(home, '.claude'), { recursive: true })
  if (anchor !== undefined) {
    writeFileSync(join(home, '.claude', 'strapped.json'), JSON.stringify(anchor))
  }
  return home
}

function runSync(home: string, extra: string[] = []) {
  // HOME deliberately points elsewhere: --home must fully isolate the run.
  // NODE, not process.execPath: under `bun test` execPath is bun (deploy parity).
  const res = spawnSync(NODE, [SCRIPT, '--home', home, ...extra], {
    encoding: 'utf8',
    env: { HOME: join(home, 'decoy-home'), PATH: process.env.PATH },
  })
  const json: SyncJson | null = res.status === 0 ? (JSON.parse(res.stdout) as SyncJson) : null
  return { ...res, json }
}

const wrapperFile = (home: string, chain: string): string =>
  join(home, '.claude', 'skills', `strapped-run-${chain}`, 'SKILL.md')

test('writes wrappers for builtins + config chains with marker, chain_source, and delegation line', () => {
  const home = makeHome({ stateRoot: '/abs/state', chains: { automode: ['plan', 'implement', 'pr'] } })
  const res = runSync(home)
  assert.equal(res.status, 0, res.stderr)
  assert.ok(res.json)
  assert.deepEqual(res.json.written.sort(), ['auto', 'automode', 'ship'])
  assert.deepEqual(res.json.unchanged, [])
  assert.deepEqual(res.json.pruned, [])

  const automode = readFileSync(wrapperFile(home, 'automode'), 'utf8')
  assert.match(automode, /^name: strapped-run-automode$/m)
  assert.match(automode, /^description: Run the strapped 'automode' chain \(plan, implement, pr\) to completion — generated by strapped, do not edit$/m)
  assert.match(automode, /^generated_by: strapped$/m)
  assert.match(automode, /^chain_source: anchor$/m)
  assert.ok(automode.includes('`/strapped:run automode $ARGUMENTS`'), automode)

  const ship = readFileSync(wrapperFile(home, 'ship'), 'utf8')
  assert.match(ship, /^chain_source: builtin$/m)
  assert.ok(ship.includes('`/strapped:run ship $ARGUMENTS`'))
})

test('second run → all unchanged', () => {
  const home = makeHome({ chains: { automode: ['plan', 'implement', 'pr'] } })
  assert.equal(runSync(home).status, 0)
  const again = runSync(home)
  assert.equal(again.status, 0, again.stderr)
  assert.ok(again.json)
  assert.deepEqual(again.json.written, [])
  assert.deepEqual(again.json.unchanged.sort(), ['auto', 'automode', 'ship'])
  assert.deepEqual(again.json.pruned, [])
})

test('removed anchor chain → wrapper pruned; unmarked sibling dir untouched', () => {
  const home = makeHome({ chains: { automode: ['plan', 'implement', 'pr'] } })
  assert.equal(runSync(home).status, 0)

  // A user-authored skill squatting on the wrapper namespace, without the marker.
  const manualDir = join(home, '.claude', 'skills', 'strapped-run-manual')
  mkdirSync(manualDir, { recursive: true })
  const manualContent = '---\nname: strapped-run-manual\ndescription: mine\n---\nhands off\n'
  writeFileSync(join(manualDir, 'SKILL.md'), manualContent)

  // The anchor chain disappears; its wrapper must be pruned, the manual one kept.
  writeFileSync(join(home, '.claude', 'strapped.json'), JSON.stringify({ chains: {} }))
  const res = runSync(home)
  assert.equal(res.status, 0, res.stderr)
  assert.ok(res.json)
  assert.deepEqual(res.json.pruned, ['automode'])
  assert.ok(!existsSync(wrapperFile(home, 'automode')), 'stale marked wrapper must be deleted')
  assert.equal(readFileSync(join(manualDir, 'SKILL.md'), 'utf8'), manualContent, 'unmarked dir must be untouched')
  // Builtin wrappers still resolve → unchanged, never pruned.
  assert.deepEqual(res.json.unchanged.sort(), ['auto', 'ship'])
})

test('an existing unmarked file at a wrapper path is never overwritten', () => {
  const home = makeHome({ chains: { automode: ['plan', 'implement', 'pr'] } })
  const dir = join(home, '.claude', 'skills', 'strapped-run-automode')
  mkdirSync(dir, { recursive: true })
  const mine = '---\nname: strapped-run-automode\ndescription: mine\n---\nhands off\n'
  writeFileSync(join(dir, 'SKILL.md'), mine)

  const res = runSync(home)
  assert.equal(res.status, 0, res.stderr)
  assert.ok(res.json)
  assert.ok(!res.json.written.includes('automode'))
  assert.equal(readFileSync(join(dir, 'SKILL.md'), 'utf8'), mine)
  assert.match(res.stderr, /without the "generated_by: strapped" marker/)
})

test('--dry-run reports but writes nothing', () => {
  const home = makeHome({ chains: { automode: ['plan', 'implement', 'pr'] } })
  const res = runSync(home, ['--dry-run'])
  assert.equal(res.status, 0, res.stderr)
  assert.ok(res.json)
  assert.deepEqual(res.json.written.sort(), ['auto', 'automode', 'ship'])
  assert.ok(!existsSync(join(home, '.claude', 'skills')), 'dry run must create nothing')
})

test('--dry-run reports a would-be prune without deleting', () => {
  const home = makeHome({ chains: { automode: ['plan', 'implement', 'pr'] } })
  assert.equal(runSync(home).status, 0)
  writeFileSync(join(home, '.claude', 'strapped.json'), JSON.stringify({}))

  const res = runSync(home, ['--dry-run'])
  assert.equal(res.status, 0, res.stderr)
  assert.ok(res.json)
  assert.deepEqual(res.json.pruned, ['automode'])
  assert.ok(existsSync(wrapperFile(home, 'automode')), 'dry run must not delete')
})
