// GENERATED by tools/build.ts from src/workflows/strapped-run/types.ts — do not edit; rebuild: bun run build
// types.ts is the single source of truth; ts-json-schema-generator derives these.

/** Derived from the `PlanResult` interface in types.ts. */
export const PLAN_SCHEMA = {
  "type": "object",
  "properties": {
    "deliverables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "deps": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "id",
          "file",
          "title",
          "deps"
        ],
        "additionalProperties": false
      }
    },
    "summary": {
      "type": "string"
    }
  },
  "required": [
    "deliverables",
    "summary"
  ],
  "additionalProperties": false
}

/** Derived from the `FindingsResult` interface in types.ts. */
export const FINDINGS_SCHEMA = {
  "type": "object",
  "properties": {
    "findings": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "key": {
            "type": "string",
            "description": "<rule-id-or-gap>:<location>, stable across rounds for dedup"
          },
          "rule": {
            "type": [
              "string",
              "null"
            ]
          },
          "severity": {
            "type": "string",
            "enum": [
              "blocking",
              "concern",
              "suggestion"
            ]
          },
          "location": {
            "type": "string"
          },
          "what": {
            "type": "string"
          },
          "why": {
            "type": "string"
          },
          "evidence": {
            "type": "string"
          },
          "confidence": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
          },
          "recommendation": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "key",
          "rule",
          "severity",
          "location",
          "what",
          "why",
          "evidence",
          "confidence",
          "recommendation"
        ],
        "additionalProperties": false
      }
    },
    "rule_checklist": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "rule": {
            "type": "string"
          },
          "verdict": {
            "type": "string",
            "enum": [
              "pass",
              "violation",
              "na"
            ]
          },
          "evidence": {
            "type": "string"
          }
        },
        "required": [
          "rule",
          "verdict",
          "evidence"
        ],
        "additionalProperties": false
      }
    },
    "ac_checklist": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "verdict": {
            "type": "string",
            "enum": [
              "pass",
              "violation",
              "na"
            ]
          },
          "evidence": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "verdict",
          "evidence"
        ],
        "additionalProperties": false,
        "description": "One reviewer verdict on a single enumerated acceptance-criterion item. Kept as its OWN required list (not folded into `rule_checklist`) so a reviewer can never silently omit the per-item AC verdicts: a required, separate field is enforced by the structured-output schema every round, giving ACs the same weight as guideline rules."
      },
      "description": "Per-item AC verdicts — required (may be empty when the artifact has no enumerated section)."
    }
  },
  "required": [
    "findings",
    "rule_checklist",
    "ac_checklist"
  ],
  "additionalProperties": false
}

/** Derived from the `VerifyResult` interface in types.ts. */
export const VERIFY_SCHEMA = {
  "type": "object",
  "properties": {
    "verdicts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The adjudicated finding's id."
          },
          "verdict": {
            "type": "string",
            "enum": [
              "confirmed",
              "plausible",
              "refuted"
            ]
          },
          "confidence": {
            "type": "number",
            "minimum": 0,
            "maximum": 100
          },
          "evidence": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "verdict",
          "confidence",
          "evidence"
        ],
        "additionalProperties": false,
        "description": "One per-finding verdict cast by the verify-consolidate agent."
      },
      "description": "One verdict per gating finding adjudicated this round."
    },
    "new_confirmed_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "duplicate_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "verdicts",
    "new_confirmed_ids",
    "duplicate_ids"
  ],
  "additionalProperties": false
}

/** Derived from the `ImplementResult` interface in types.ts. */
export const IMPLEMENT_SCHEMA = {
  "type": "object",
  "properties": {
    "status": {
      "type": "string",
      "enum": [
        "implemented",
        "blocked"
      ]
    },
    "summary": {
      "type": "string"
    },
    "validations_green": {
      "type": "boolean"
    },
    "blocker": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "status",
    "summary",
    "validations_green",
    "blocker"
  ],
  "additionalProperties": false
}

/** Derived from the `WaveResult` interface in types.ts. */
export const WAVE_SCHEMA = {
  "type": "object",
  "properties": {
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "repo": {
            "type": "string"
          },
          "repoRoot": {
            "type": "string"
          },
          "validations": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "planFile": {
            "type": "string"
          },
          "worktree": {
            "type": "string"
          },
          "branch": {
            "type": "string"
          },
          "base": {
            "type": "string"
          },
          "resumeNote": {
            "type": [
              "string",
              "null"
            ]
          },
          "pr": {
            "type": [
              "string",
              "null"
            ],
            "description": "the node's `pr:` frontmatter URL, null for a pre-PR node"
          }
        },
        "required": [
          "id",
          "repo",
          "repoRoot",
          "validations",
          "planFile",
          "worktree",
          "branch",
          "base",
          "resumeNote",
          "pr"
        ],
        "additionalProperties": false
      }
    },
    "dag": {
      "type": "object",
      "properties": {
        "ready": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "resumable": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "In-progress node ids from the dag's nodes list — interrupted implementations this pass may resume."
        },
        "remaining": {
          "type": "number"
        },
        "blocked": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "blockedOn": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "id",
              "blockedOn"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "ready",
        "resumable",
        "remaining",
        "blocked"
      ],
      "additionalProperties": false,
      "description": "The workflow trusts this paste: `remaining`/`blocked` are read from here verbatim."
    }
  },
  "required": [
    "items",
    "dag"
  ],
  "additionalProperties": false
}

/** Derived from the `ApplyResult` interface in types.ts. */
export const APPLY_SCHEMA = {
  "type": "object",
  "properties": {
    "applied": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "done",
              "parked",
              "pr-open"
            ]
          }
        },
        "required": [
          "id",
          "status"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "applied"
  ],
  "additionalProperties": false
}

/** Derived from the `ApproveResult` interface in types.ts. */
export const APPROVE_SCHEMA = {
  "type": "object",
  "properties": {
    "changed": {
      "type": "boolean"
    }
  },
  "required": [
    "changed"
  ],
  "additionalProperties": false
}

/** Derived from the `ProbeResult` interface in types.ts. */
export const PROBE_SCHEMA = {
  "type": "object",
  "properties": {
    "remaining": {
      "type": "number"
    },
    "notDone": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "remaining",
    "notDone"
  ],
  "additionalProperties": false
}

/** Derived from the `PrResult` interface in types.ts. */
export const PR_SCHEMA = {
  "type": "object",
  "properties": {
    "prs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "url": {
            "type": [
              "string",
              "null"
            ]
          },
          "skipped": {
            "type": "boolean"
          },
          "reason": {
            "type": [
              "string",
              "null"
            ]
          }
        },
        "required": [
          "id",
          "url",
          "skipped",
          "reason"
        ],
        "additionalProperties": false
      }
    },
    "summary": {
      "type": "string"
    }
  },
  "required": [
    "prs",
    "summary"
  ],
  "additionalProperties": false
}

/** Derived from the `PlanLeadResult` interface in types.ts. */
export const PLAN_LEAD_SCHEMA = {
  "type": "object",
  "properties": {
    "deliverables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "deps": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "id",
          "file",
          "title",
          "deps"
        ],
        "additionalProperties": false
      }
    },
    "summary": {
      "type": "string"
    },
    "research_requests": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "topic": {
            "type": "string"
          },
          "brief": {
            "type": "string"
          }
        },
        "required": [
          "topic",
          "brief"
        ],
        "additionalProperties": false,
        "description": "One research topic a planner or researcher enqueues for a later BFS round."
      },
      "description": "Empty = the small-ask exit: the planner already wrote every plan artifact itself."
    }
  },
  "required": [
    "deliverables",
    "summary",
    "research_requests"
  ],
  "additionalProperties": false
}

/** Derived from the `ResearchResult` interface in types.ts. */
export const RESEARCH_SCHEMA = {
  "type": "object",
  "properties": {
    "topic": {
      "type": "string"
    },
    "notes_file": {
      "type": "string"
    },
    "summary": {
      "type": "string"
    },
    "research_requests": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "topic": {
            "type": "string"
          },
          "brief": {
            "type": "string"
          }
        },
        "required": [
          "topic",
          "brief"
        ],
        "additionalProperties": false,
        "description": "One research topic a planner or researcher enqueues for a later BFS round."
      }
    }
  },
  "required": [
    "topic",
    "notes_file",
    "summary",
    "research_requests"
  ],
  "additionalProperties": false
}

/** Derived from the `ResearchFinalResult` interface in types.ts. */
export const RESEARCH_FINAL_SCHEMA = {
  "type": "object",
  "properties": {
    "topic": {
      "type": "string"
    },
    "notes_file": {
      "type": "string"
    },
    "summary": {
      "type": "string"
    }
  },
  "required": [
    "topic",
    "notes_file",
    "summary"
  ],
  "additionalProperties": false
}
