// Deterministic build pipeline: bundles each src/scripts/<name>.ts entry into
// its committed, node-runnable deployable (zero runtime dependencies, shebang +
// GENERATED header, exec bit). Determinism is pinned by .tool-versions +
// bun.lock; tests/build-sync.test.ts runs `--check` so an unrebuilt src/ edit
// fails the suite.
//
//   bun tools/build.ts           write all artifacts
//   bun tools/build.ts --check   build to memory, byte-compare committed
//                                artifacts, exit 1 listing stale files

import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

export interface BuildSpec {
  /** Repo-relative TS entrypoint. */
  entry: string
  /** Repo-relative committed artifact path (skills reference it verbatim). */
  outfile: string
}

// Registry of deployables. D2 (state, sync-chain-skills) and D3 (workflow)
// append here.
export const BUILDS: readonly BuildSpec[] = [
  { entry: 'src/scripts/resolve-chain.ts', outfile: 'plugins/strapped/scripts/resolve-chain.mjs' },
]

/** Bundle one CLI entry and return the finished artifact text (in memory). */
export async function buildCli(spec: BuildSpec): Promise<string> {
  // Bun's bundler emits source-path comments relative to the process cwd; pin
  // it for the build so artifacts are byte-identical no matter where the build
  // is invoked from (restored right after — tests import this module).
  const prevCwd = process.cwd()
  process.chdir(ROOT)
  let result: Awaited<ReturnType<typeof Bun.build>>
  try {
    result = await Bun.build({
      entrypoints: [resolve(ROOT, spec.entry)],
      target: 'node',
      format: 'esm',
      minify: false,
      sourcemap: 'none',
    })
  } finally {
    process.chdir(prevCwd)
  }
  if (!result.success) {
    throw new Error(`build failed for ${spec.entry}:\n${result.logs.map(l => String(l)).join('\n')}`)
  }
  const artifact = result.outputs[0]
  if (!artifact || result.outputs.length !== 1) {
    throw new Error(`build for ${spec.entry} produced ${result.outputs.length} outputs, expected exactly 1`)
  }
  let code = await artifact.text()
  // Bun may forward a source shebang; ours is authored here, exactly once.
  if (code.startsWith('#!')) code = code.slice(code.indexOf('\n') + 1)
  return (
    '#!/usr/bin/env node\n' +
    `// GENERATED by tools/build.ts from ${spec.entry} — do not edit; rebuild: bun run build\n` +
    code
  )
}

/** Build every spec in memory and return the outfiles whose committed bytes differ. */
export async function findStale(specs: readonly BuildSpec[]): Promise<string[]> {
  const stale: string[] = []
  for (const spec of specs) {
    const expected = await buildCli(spec)
    const path = resolve(ROOT, spec.outfile)
    const actual = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (actual !== expected) stale.push(spec.outfile)
  }
  return stale
}

async function main(): Promise<void> {
  const check = process.argv.slice(2).includes('--check')
  if (check) {
    const stale = await findStale(BUILDS)
    if (stale.length > 0) {
      process.stderr.write(
        `tools/build.ts: stale generated artifacts:\n${stale.map(f => `  ${f}`).join('\n')}\n` +
          'run `bun run build` and commit the result\n'
      )
      process.exit(1)
    }
    return
  }
  for (const spec of BUILDS) {
    const path = resolve(ROOT, spec.outfile)
    writeFileSync(path, await buildCli(spec))
    chmodSync(path, 0o755)
    process.stdout.write(`built ${spec.outfile} from ${spec.entry}\n`)
  }
}

if (import.meta.main) await main()
