// Derives the strapped-run agent JSON schemas from the TypeScript interfaces in
// src/workflows/strapped-run/types.ts — types.ts is the single source of truth.
// ts-json-schema-generator reads the interfaces (enums as string-literal unions,
// numeric bounds as JSDoc @minimum/@maximum, nullable as `T | null`, field docs
// as JSDoc, additionalProperties forced false) and emits the same inline schema
// objects agent() consumes. tools/build.ts emits the constants into the committed
// src/workflows/strapped-run/schemas.generated.ts; tests/schema-equivalence
// deep-equals them against the frozen tests/fixtures/schemas.snapshot.json.

import { createGenerator } from 'ts-json-schema-generator'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

/**
 * Agent-result interface → exported schema-constant name, in the emission order
 * of the original hand-written schemas.ts (keeps the committed diff clean).
 */
export const SCHEMA_TYPES: ReadonlyArray<readonly [type: string, constant: string]> = [
  ['PlanResult', 'PLAN_SCHEMA'],
  ['FindingsResult', 'FINDINGS_SCHEMA'],
  ['VerifyResult', 'VERIFY_SCHEMA'],
  ['ImplementResult', 'IMPLEMENT_SCHEMA'],
  ['WaveResult', 'WAVE_SCHEMA'],
  ['ApplyResult', 'APPLY_SCHEMA'],
  ['ApproveResult', 'APPROVE_SCHEMA'],
  ['ProbeResult', 'PROBE_SCHEMA'],
  ['PrResult', 'PR_SCHEMA'],
  ['PlanLeadResult', 'PLAN_LEAD_SCHEMA'],
  ['ResearchResult', 'RESEARCH_SCHEMA'],
  ['ResearchFinalResult', 'RESEARCH_FINAL_SCHEMA'],
]

type SchemaGenerator = ReturnType<typeof createGenerator>

function makeGenerator(): SchemaGenerator {
  return createGenerator({
    path: resolve(ROOT, 'src/workflows/strapped-run/types.ts'),
    tsconfig: resolve(ROOT, 'tsconfig.json'),
    // Inline every referenced type and drop the $ref/definitions wrapper so
    // each schema is the flat inline object agent() is passed today.
    expose: 'none',
    topRef: false,
    // Pick up @minimum / @maximum / field descriptions from JSDoc.
    jsDoc: 'extended',
    // Force additionalProperties:false on interfaces (they carry no index sigs).
    additionalProperties: false,
    sortProps: false,
    skipTypeCheck: true,
  })
}

/**
 * Strip the wrapper keys ts-json-schema-generator adds at the schema root
 * ($schema meta, the empty definitions map, and the root `description` derived
 * from the interface's own `/** X_SCHEMA *\/` doc comment) so the result is the
 * bare inline object shape the hand-written constants had. Field-level
 * descriptions live inside `properties` and are untouched.
 */
function stripRootWrapper(schema: Record<string, unknown>): Record<string, unknown> {
  const { $schema, definitions, description, ...rest } = schema
  void $schema
  void definitions
  void description
  return rest
}

/** Generate every agent schema, keyed by its exported constant name. */
export function generateSchemas(): Record<string, Record<string, unknown>> {
  const gen = makeGenerator()
  const out: Record<string, Record<string, unknown>> = {}
  for (const [type, constant] of SCHEMA_TYPES) {
    out[constant] = stripRootWrapper(gen.createSchema(type) as Record<string, unknown>)
  }
  return out
}

/** Emit the committed src/workflows/strapped-run/schemas.generated.ts text. */
export function emitSchemasModule(): string {
  const schemas = generateSchemas()
  const body = SCHEMA_TYPES.map(([type, constant]) => {
    const json = JSON.stringify(schemas[constant], null, 2)
    return `/** Derived from the \`${type}\` interface in types.ts. */\nexport const ${constant} = ${json}\n`
  }).join('\n')
  return (
    '// GENERATED by tools/build.ts from src/workflows/strapped-run/types.ts — do not edit; rebuild: bun run build\n' +
    '// types.ts is the single source of truth; ts-json-schema-generator derives these.\n\n' +
    body
  )
}
